# Project on Kidney Disease CKD dataset

IMPORTING THE LIBRARIES

In [1]:
#####  Imported the necessary dependencies 
import pandas as pd 
import numpy as np

LOADING THE DATASET

In [2]:
Data=pd.read_csv(r"C:\Users\harik\OneDrive\Desktop\VCUBE Works\Ckd.rpoject\Kidney-Dataset(CKD).csv") # To read the datset

pd.set_option('display.max_columns', None)  # To display all columns
pd.set_option('display.max_rows', None)   # To display all rows

Data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.20,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.80,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.80,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.80,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.40,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,25.0,1.10,142.0,3.2,12.2,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,54.0,24.00,104.0,4.0,12.4,36,NaN,NaN,no,no,no,good,no,no,ckd
7,7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,31.0,1.10,NaN,NaN,12.4,44,6900,5,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,60.0,1.90,NaN,NaN,10.8,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,107.0,7.20,114.0,3.7,9.5,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
10,10,50.0,60.0,1.010,2.0,4.0,NaN,abnormal,present,notpresent,490.0,55.0,4.00,NaN,NaN,9.4,28,NaN,NaN,yes,yes,no,good,no,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,60.0,2.70,131.0,4.2,10.8,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
12,12,68.0,70.0,1.015,3.0,1.0,NaN,normal,present,notpresent,208.0,72.0,2.10,138.0,5.8,9.7,28,12200,3.4,yes,yes,yes,poor,yes,no,ckd
13,13,68.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,98.0,86.0,4.60,135.0,3.4,9.8,NaN,NaN,NaN,yes,yes,yes,poor,yes,no,ckd
14,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,90.0,4.10,130.0,6.4,5.6,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
15,15,40.0,80.0,1.015,3.0,0.0,NaN,normal,notpresent,notpresent,76.0,162.0,9.60,141.0,4.9,7.6,24,3800,2.8,yes,no,no,good,no,yes,ckd
16,16,47.0,70.0,1.015,2.0,0.0,NaN,normal,notpresent,notpresent,99.0,46.0,2.20,138.0,4.1,12.6,NaN,NaN,NaN,no,no,no,good,no,no,ckd
17,17,47.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,114.0,87.0,5.20,139.0,3.7,12.1,NaN,NaN,NaN,yes,no,no,poor,no,no,ckd
18,18,60.0,100.0,1.025,0.0,3.0,NaN,normal,notpresent,notpresent,263.0,27.0,1.30,135.0,4.3,12.7,37,11400,4.3,yes,yes,yes,good,no,no,ckd
19,19,62.0,60.0,1.015,1.0,0.0,NaN,abnormal,present,notpresent,100.0,31.0,1.60,NaN,NaN,10.3,30,5300,3.7,yes,no,yes,good,no,no,ckd
20,20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,148.0,3.90,135.0,5.2,7.7,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd
21,21,60.0,90.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,NaN,180.0,76.00,4.5,NaN,10.9,32,6200,3.6,yes,yes,yes,good,no,no,ckd
22,22,48.0,80.0,1.025,4.0,0.0,normal,abnormal,notpresent,notpresent,95.0,163.0,7.70,136.0,3.8,9.8,32,6900,3.4,yes,no,no,good,no,yes,ckd
23,23,21.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,poor,no,yes,ckd
24,24,42.0,100.0,1.015,4.0,0.0,normal,abnormal,notpresent,present,NaN,50.0,1.40,129.0,4.0,11.1,39,8300,4.6,yes,no,no,poor,no,no,ckd
25,25,61.0,60.0,1.025,0.0,0.0,NaN,normal,notpresent,notpresent,108.0,75.0,1.90,141.0,5.2,9.9,29,8400,3.7,yes,yes,no,good,no,yes,ckd
26,26,75.0,80.0,1.015,0.0,0.0,NaN,normal,notpresent,notpresent,156.0,45.0,2.40,140.0,3.4,11.6,35,10300,4,yes,yes,no,poor,no,no,ckd
27,27,69.0,70.0,1.010,3.0,4.0,normal,abnormal,notpresent,notpresent,264.0,87.0,2.70,130.0,4.0,12.5,37,9600,4.1,yes,yes,yes,good,yes,no,ckd
28,28,75.0,70.0,NaN,1.0,3.0,NaN,NaN,notpresent,notpresent,123.0,31.0,1.40,NaN,NaN,NaN,NaN,NaN,NaN,no,yes,no,good,no,no,ckd
29,29,68.0,70.0,1.005,1.0,0.0,abnormal,abnormal,present,notpresent,NaN,28.0,1.40,NaN,NaN,12.9,38,NaN,NaN,no,no,yes,good,no,no,ckd
30,30,NaN,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,93.0,155.0,7.30,132.0,4.9,NaN,NaN,NaN,NaN,yes,yes,no,good,no,no,ckd
31,31,73.0,90.0,1.015,3.0,0.0,NaN,abnormal,present,notpresent,107.0,33.0,1.50,141.0,4.6,10.1,30,7800,4,no,no,no,poor,no,no,ckd
32,32,61.0,90.0,1.010,1.0,1.0,NaN,normal,notpresent,notpresent,159.0,39.0,1.50,133.0,4.9,11.3,34,9600,4.0,yes,yes,no,poor,no,no,ckd
33,33,60.0,100.0,1.020,2.0,0.0,abnormal,abnormal,notpresent,notpresent,140.0,55.0,2.50,NaN,NaN,10.1,29,NaN,NaN,yes,no,no,poor,no,no,ckd
34,34,70.0,70.0,1.010,1.0,0.0,normal,NaN,present,present,171.0,153.0,5.20,NaN,NaN,NaN,NaN,NaN,NaN,no,yes,no,poor,no,no,ckd
35,35,65.0,90.0,1.020,2.0,1.0,abnormal,normal,notpresent,notpresent,270.0,39.0,2.00,NaN,NaN,12.0,36,9800,4.9,yes,yes,no,poor,no,yes,ckd
36,36,76.0,70.0,1.015,1.0,0.0,normal,normal,notpresent,notpresent,92.0,29.0,1.80,133.0,3.9,10.3,32,NaN,NaN,yes,no,no,good,no,no,ckd
37,37,72.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,137.0,65.0,3.40,141.0,4.7,9.7,28,6900,2.5,yes,yes,no,poor,no,yes,ckd\t
38,38,69.0,80.0,1.020,3.0,0.0,abnormal,normal,notpresent,notpresent,NaN,103.0,4.10,132.0,5.9,12.5,NaN,NaN,NaN,yes,no,no,good,no,no,ckd
39,39,82.0,80.0,1.010,2.0,2.0,normal,NaN,notpresent,notpresent,140.0,70.0,3.40,136.0,4.2,13.0,40,9800,4.2,yes,yes,no,good,no,no,ckd
40,40,46.0,90.0,1.010,2.0,0.0,normal,abnormal,notpresent,notpresent,99.0,80.0,2.10,NaN,NaN,11.1,32,9100,4.1,yes,no,\tno,good,no,no,ckd
41,41,45.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,NaN,20.0,0.70,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
42,42,47.0,100.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,204.0,29.0,1.00,139.0,4.2,9.7,33,9200,4.5,yes,no,no,good,no,yes,ckd
43,43,35.0,80.0,1.010,1.0,0.0,abnormal,NaN,notpresent,notpresent,79.0,202.0,10.80,134.0,3.4,7.9,24,7900,3.1,no,yes,no,good,no,no,ckd
44,44,54.0,80.0,1.010,3.0,0.0,abnormal,abnormal,notpresent,notpresent,207.0,77.0,6.30,134.0,4.8,9.7,28,NaN,NaN,yes,yes,no,poor,yes,no,ckd
45,45,54.0,80.0,1.020,3.0,0.0,NaN,abnormal,notpresent,notpresent,208.0,89.0,5.90,130.0,4.9,9.3,NaN,NaN,NaN,yes,yes,no,poor,yes,no,ckd
46,46,48.0,70.0,1.015,0.0,0.0,NaN,normal,notpresent,notpresent,124.0,24.0,1.20,142.0,4.2,12.4,37,6400,4.7,no,yes,no,good,no,no,ckd
47,47,11.0,80.0,1.010,3.0,0.0,NaN,normal,notpresent,notpresent,NaN,17.0,0.80,NaN,NaN,15.0,45,8600,NaN,no,no,no,good,no,no,ckd
48,48,73.0,70.0,1.005,0.0,0.0,normal,normal,notpresent,notpresent,70.0,32.0,0.90,125.0,4.0,10.0,29,18900,3.5,yes,yes,no,good,yes,no,ckd
49,49,60.0,70.0,1.010,2.0,0.0,normal,abnormal,present,notpresent,144.0,72.0,3.00,NaN,NaN,9.7,29,21600,3.5,yes,yes,no,poor,no,yes,ckd
50,50,53.0,60.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,91.0,114.0,3.25,142.0,4.3,8.6,28,11000,3.8,yes,yes,no,poor,yes,yes,ckd
51,51,54.0,100.0,1.015,3.0,0.0,NaN,normal,present,notpresent,162.0,66.0,1.60,136.0,4.4,10.3,33,NaN,NaN,yes,yes,no,poor,yes,no,ckd
52,52,53.0,90.0,1.015,0.0,0.0,NaN,normal,notpresent,notpresent,NaN,38.0,2.20,NaN,NaN,10.9,34,4300,3.7,no,no,no,poor,no,yes,ckd
53,53,62.0,80.0,1.015,0.0,5.0,NaN,NaN,notpresent,notpresent,246.0,24.0,1.00,NaN,NaN,13.6,40,8500,4.7,yes,yes,no,good,no,no,ckd
54,54,63.0,80.0,1.010,2.0,2.0,normal,NaN,notpresent,notpresent,NaN,NaN,3.40,136.0,4.2,13.0,40,9800,4.2,yes,no,yes,good,no,no,ckd
55,55,35.0,80.0,1.005,3.0,0.0,abnormal,normal,notpresent,notpresent,NaN,NaN,NaN,NaN,NaN,9.5,28,NaN,NaN,no,no,no,good,yes,no,ckd
56,56,76.0,70.0,1.015,3.0,4.0,normal,abnormal,present,notpresent,NaN,164.0,9.70,131.0,4.4,10.2,30,11300,3.4,yes,yes,yes,poor,yes,no,ckd
57,57,76.0,90.0,NaN,NaN,NaN,NaN,normal,notpresent,notpresent,93.0,155.0,7.30,132.0,4.9,NaN,NaN,NaN,NaN,yes,yes,yes,poor,no,no,ckd
58,58,73.0,80.0,1.020,2.0,0.0,abnormal,abnormal,notpresent,notpresent,253.0,142.0,4.60,138.0,5.8,10.5,33,7200,4.3,yes,yes,yes,good,no,no,ckd
59,59,59.0,100.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,NaN,96.0,6.40,NaN,NaN,6.6,NaN,NaN,NaN,yes,yes,no,good,no,yes,ckd
60,60,67.0,90.0,1.020,1.0,0.0,NaN,abnormal,present,notpresent,141.0,66.0,3.20,138.0,6.6,NaN,NaN,NaN,NaN,yes,no,no,good,no,no,ckd
61,61,67.0,80.0,1.010,1.0,3.0,normal,abnormal,notpresent,notpresent,182.0,391.0,32.00,163.0,39.0,NaN,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
62,62,15.0,60.0,1.020,3.0,0.0,NaN,normal,notpresent,notpresent,86.0,15.0,0.60,138.0,4.0,11.0,33,7700,3.8,yes,yes,no,good,no,no,ckd
63,63,46.0,70.0,1.015,1.0,0.0,abnormal,normal,notpresent,notpresent,150.0,111.0,6.10,131.0,3.7,7.5,27,NaN,NaN,no,no,no,good,no,yes,ckd
64,64,55.0,80.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,146.0,NaN,NaN,NaN,NaN,9.8,NaN,NaN,NaN,no,no,\tno,good,no,no,ckd
65,65,44.0,90.0,1.010,1.0,0.0,NaN,normal,notpresent,notpresent,NaN,20.0,1.10,NaN,NaN,15.0,48,NaN,NaN,no,\tno,no,good,no,no,ckd
66,66,67.0,70.0,1.020,2.0,0.0,abnormal,normal,notpresent,notpresent,150.0,55.0,1.60,131.0,4.8,NaN,\t?,NaN,NaN,yes,yes,no,good,yes,no,ckd
67,67,45.0,80.0,1.020,3.0,0.0,normal,abnormal,notpresent,notpresent,425.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,poor,no,no,ckd
68,68,65.0,70.0,1.010,2.0,0.0,NaN,normal,present,notpresent,112.0,73.0,3.30,NaN,NaN,10.9,37,NaN,NaN,no,no,no,good,no,no,ckd
69,69,26.0,70.0,1.015,0.0,4.0,NaN,normal,notpresent,notpresent,250.0,20.0,1.10,NaN,NaN,15.6,52,6900,6.0,no,yes,no,good,no,no,ckd
70,70,61.0,80.0,1.015,0.0,4.0,NaN,normal,notpresent,notpresent,360.0,19.0,0.70,137.0,4.4,15.2,44,8300,5.2,yes,yes,no,good,no,no,ckd
71,71,46.0,60.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,163.0,92.0,3.30,141.0,4.0,9.8,28,14600,3.2,yes,yes,no,good,no,no,ckd
72,72,64.0,90.0,1.010,3.0,3.0,NaN,abnormal,present,notpresent,NaN,35.0,1.30,NaN,NaN,10.3,NaN,NaN,NaN,yes,yes,no,good,yes,no,ckd
73,73,NaN,100.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,129.0,107.0,6.70,132.0,4.4,4.8,14,6300,NaN,yes,no,no,good,yes,yes,ckd
74,74,56.0,90.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,129.0,107.0,6.70,131.0,4.8,9.1,29,6400,3.4,yes,no,no,good,no,no,ckd
75,75,5.0,NaN,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,NaN,16.0,0.70,138.0,3.2,8.1,NaN,NaN,NaN,no,no,no,good,no,yes,ckd
76,76,48.0,80.0,1.005,4.0,0.0,abnormal,abnormal,notpresent,present,133.0,139.0,8.50,132.0,5.5,10.3,36,\t6200,4,no,yes,no,good,yes,no,ckd
77,77,67.0,70.0,1.010,1.0,0.0,NaN,normal,notpresent,notpresent,102.0,48.0,3.20,137.0,5.0,11.9,34,7100,3.7,yes,yes,no,good,yes,no,ckd
78,78,70.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,158.0,85.0,3.20,141.0,3.5,10.1,30,NaN,NaN,yes,no,no,good,yes,no,ckd
79,79,56.0,80.0,1.010,1.0,0.0,NaN,normal,notpresent,notpresent,165.0,55.0,1.80,NaN,NaN,13.5,40,11800,5.0,yes,yes,no,poor,yes,no,ckd
80,80,74.0,80.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,132.0,98.0,2.80,133.0,5.0,10.8,31,9400,3.8,yes,yes,no,good,no,no,ckd
81,81,45.0,90.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,360.0,45.0,2.40,128.0,4.4,8.3,29,5500,3.7,yes,yes,no,good,no,no,ckd
82,82,38.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,104.0,77.0,1.90,140.0,3.9,NaN,NaN,NaN,NaN,yes,no,no,poor,yes,no,ckd
83,83,48.0,70.0,1.015,1.0,0.0,normal,normal,notpresent,notpresent,127.0,19.0,1.00,134.0,3.6,NaN,NaN,NaN,NaN,yes,yes,no,good,no,no,ckd
84,84,59.0,70.0,1.010,3.0,0.0,normal,abnormal,notpresent,notpresent,76.0,186.0,15.00,135.0,7.6,7.1,22,3800,2.1,yes,no,no,poor,yes,yes,ckd
85,85,70.0,70.0,1.015,2.0,NaN,NaN,NaN,notpresent,notpresent,NaN,46.0,1.50,NaN,NaN,9.9,NaN,NaN,NaN,no,yes,no,poor,yes,no,ckd
86,86,56.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,415.0,37.0,1.90,NaN,NaN,NaN,NaN,NaN,NaN,no,yes,no,good,no,no,ckd
87,87,70.0,100.0,1.005,1.0,0.0,normal,abnormal,present,notpresent,169.0,47.0,2.90,NaN,NaN,11.1,32,5800,5,yes,yes,no,poor,no,no,ckd
88,88,58.0,110.0,1.010,4.0,0.0,NaN,normal,notpresent,notpresent,251.0,52.0,2.20,NaN,NaN,NaN,NaN,13200,4.7,yes,\tyes,no,good,no,no,ckd
89,89,50.0,70.0,1.020,0.0,0.0,NaN,normal,notpresent,notpresent,109.0,32.0,1.40,139.0,4.7,NaN,NaN,NaN,NaN,no,no,no,poor,no,no,ckd
90,90,63.0,100.0,1.010,2.0,2.0,normal,normal,notpresent,present,280.0,35.0,3.20,143.0,3.5,13.0,40,9800,4.2,yes,no,yes,good,no,no,ckd
91,91,56.0,70.0,1.015,4.0,1.0,abnormal,normal,notpresent,notpresent,210.0,26.0,1.70,136.0,3.8,16.1,52,12500,5.6,no,no,no,good,no,no,ckd
92,92,71.0,70.0,1.010,3.0,0.0,normal,abnormal,present,present,219.0,82.0,3.60,133.0,4.4,10.4,33,5600,3.6,yes,yes,yes,good,no,no,ckd
93,93,73.0,100.0,1.010,3.0,2.0,abnormal,abnormal,present,notpresent,295.0,90.0,5.60,140.0,2.9,9.2,30,7000,3.2,yes,yes,yes,poor,no,no,ckd
94,94,65.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,93.0,66.0,1.60,137.0,4.5,11.6,36,11900,3.9,no,yes,no,good,no,no,ckd
95,95,62.0,90.0,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,94.0,25.0,1.10,131.0,3.7,NaN,NaN,NaN,NaN,yes,no,no,good,yes,yes,ckd
96,96,60.0,80.0,1.010,1.0,1.0,NaN,normal,notpresent,notpresent,172.0,32.0,2.70,NaN,NaN,11.2,36,NaN,NaN,no,yes,yes,poor,no,no,ckd
97,97,65.0,60.0,1.015,1.0,0.0,NaN,normal,notpresent,notpresent,91.0,51.0,2.20,132.0,3.8,10.0,32,9100,4.0,yes,yes,no,poor,yes,no,ckd
98,98,50.0,140.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,101.0,106.0,6.50,135.0,4.3,6.2,18,5800,2.3,yes,yes,no,poor,no,yes,ckd
99,99,56.0,180.0,NaN,0.0,4.0,NaN,abnormal,notpresent,notpresent,298.0,24.0,1.20,139.0,3.9,11.2,32,10400,4.2,yes,yes,no,poor,yes,no,ckd
100,100,34.0,70.0,1.015,4.0,0.0,abnormal,abnormal,notpresent,notpresent,153.0,22.0,0.90,133.0,3.8,NaN,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
101,101,71.0,90.0,1.015,2.0,0.0,NaN,abnormal,present,present,88.0,80.0,4.40,139.0,5.7,11.3,33,10700,3.9,no,no,no,good,no,no,ckd
102,102,17.0,60.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,92.0,32.0,2.10,141.0,4.2,13.9,52,7000,NaN,no,no,no,good,no,no,ckd
103,103,76.0,70.0,1.015,2.0,0.0,normal,abnormal,present,notpresent,226.0,217.0,10.20,NaN,NaN,10.2,36,12700,4.2,yes,no,no,poor,yes,yes,ckd
104,104,55.0,90.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,143.0,88.0,2.00,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,poor,yes,no,ckd
105,105,65.0,80.0,1.015,0.0,0.0,NaN,normal,notpresent,notpresent,115.0,32.0,11.50,139.0,4.0,14.1,42,6800,5.2,no,no,no,good,no,no,ckd
106,106,50.0,90.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,89.0,118.0,6.10,127.0,4.4,6.0,17,6500,NaN,yes,yes,no,good,yes,yes,ckd
107,107,55.0,100.0,1.015,1.0,4.0,normal,NaN,notpresent,notpresent,297.0,53.0,2.80,139.0,4.5,11.2,34,13600,4.4,yes,yes,no,good,no,no,ckd
108,108,45.0,80.0,1.015,0.0,0.0,NaN,abnormal,notpresent,notpresent,107.0,15.0,1.00,141.0,4.2,11.8,37,10200,4.2,no,no,no,good,no,no,ckd
109,109,54.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,233.0,50.1,1.90,NaN,NaN,11.7,NaN,NaN,NaN,no,yes,no,good,no,no,ckd
110,110,63.0,90.0,1.015,0.0,0.0,NaN,normal,notpresent,notpresent,123.0,19.0,2.00,142.0,3.8,11.7,34,11400,4.7,no,no,no,good,no,no,ckd
111,111,65.0,80.0,1.010,3.0,3.0,NaN,normal,notpresent,notpresent,294.0,71.0,4.40,128.0,5.4,10.0,32,9000,3.9,yes,yes,yes,good,no,no,ckd
112,112,NaN,60.0,1.015,3.0,0.0,abnormal,abnormal,notpresent,notpresent,NaN,34.0,1.20,NaN,NaN,10.8,33,NaN,NaN,no,no,no,good,no,no,ckd
113,113,61.0,90.0,1.015,0.0,2.0,NaN,normal,notpresent,notpresent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9800,NaN,no,yes,no,poor,no,yes,ckd
114,114,12.0,60.0,1.015,3.0,0.0,abnormal,abnormal,present,notpresent,NaN,51.0,1.80,NaN,NaN,12.1,NaN,10300,NaN,no,no,no,good,no,no,ckd
115,115,47.0,80.0,1.010,0.0,0.0,NaN,abnormal,notpresent,notpresent,NaN,28.0,0.90,NaN,NaN,12.4,44,5600,4.3,no,no,no,good,no,yes,ckd
116,116,NaN,70.0,1.015,4.0,0.0,abnormal,normal,notpresent,notpresent,104.0,16.0,0.50,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,good,yes,no,ckd
117,117,NaN,70.0,1.020,0.0,0.0,NaN,NaN,notpresent,notpresent,219.0,36.0,1.30,139.0,3.7,12.5,37,9800,4.4,no,no,no,good,no,no,ckd
118,118,55.0,70.0,1.010,3.0,0.0,NaN,normal,notpresent,notpresent,99.0,25.0,1.20,NaN,NaN,11.4,NaN,NaN,NaN,no,no,no,poor,yes,no,ckd
119,119,60.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,140.0,27.0,1.20,NaN,NaN,NaN,NaN,NaN,NaN,no,no,no,good,no,no,ckd
120,120,72.0,90.0,1.025,1.0,3.0,NaN,normal,notpresent,notpresent,323.0,40.0,2.20,137.0,5.3,12.6,NaN,NaN,NaN,no,yes,yes,poor,no,no,ckd
121,121,54.0,60.0,NaN,3.0,NaN,NaN,NaN,notpresent,notpresent,125.0,21.0,1.30,137.0,3.4,15.0,46,NaN,NaN,yes,yes,no,good,yes,no,ckd
122,122,34.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,NaN,219.0,12.20,130.0,3.8,6.0,NaN,NaN,NaN,yes,no,no,good,no,yes,ckd
123,123,43.0,80.0,1.015,2.0,3.0,NaN,abnormal,present,present,NaN,30.0,1.10,NaN,NaN,14.0,42,14900,NaN,no,no,no,good,no,no,ckd
124,124,65.0,100.0,1.015,0.0,0.0,NaN,normal,notpresent,notpresent,90.0,98.0,2.50,NaN,NaN,9.1,28,5500,3.6,yes,no,no,good,no,no,ckd
125,125,72.0,90.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,308.0,36.0,2.50,131.0,4.3,NaN,NaN,NaN,NaN,yes,yes,no,poor,no,no,ckd
126,126,70.0,90.0,1.015,0.0,0.0,NaN,normal,notpresent,notpresent,144.0,125.0,4.00,136.0,4.6,12.0,37,8200,4.5,yes,yes,no,poor,yes,no,ckd
127,127,71.0,60.0,1.015,4.0,0.0,normal,normal,notpresent,notpresent,118.0,125.0,5.30,136.0,4.9,11.4,35,15200,4.3,yes,yes,no,poor,yes,no,ckd
128,128,52.0,90.0,1.015,4.0,3.0,normal,abnormal,notpresent,notpresent,224.0,166.0,5.60,133.0,47.0,8.1,23,5000,2.9,yes,yes,no,good,no,yes,ckd
129,129,75.0,70.0,1.025,1.0,0.0,NaN,normal,notpresent,notpresent,158.0,49.0,1.40,135.0,4.7,11.1,NaN,NaN,NaN,yes,no,no,poor,yes,no,ckd
130,130,50.0,90.0,1.010,2.0,0.0,normal,abnormal,present,present,128.0,208.0,9.20,134.0,4.8,8.2,22,16300,2.7,no,no,no,poor,yes,yes,ckd
131,131,5.0,50.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,NaN,25.0,0.60,NaN,NaN,11.8,36,12400,NaN,no,no,no,good,no,no,ckd
132,132,50.0,NaN,NaN,NaN,NaN,normal,NaN,notpresent,notpresent,219.0,176.0,13.80,136.0,4.5,8.6,24,13200,2.7,yes,no,no,good,yes,yes,ckd
133,133,70.0,100.0,1.015,4.0,0.0,normal,normal,notpresent,notpresent,118.0,125.0,5.30,136.0,4.9,12.0,37,\t8400,8.0,yes,no,no,good,no,no,ckd
134,134,47.0,100.0,1.010,NaN,NaN,normal,NaN,notpresent,notpresent,122.0,NaN,16.90,138.0,5.2,10.8,33,10200,3.8,no,yes,no,good,no,no,ckd
135,135,48.0,80.0,1.015,0.0,2.0,NaN,normal,notpresent,notpresent,214.0,24.0,1.30,140.0,4.0,13.2,39,NaN,NaN,no,yes,no,poor,no,no,ckd
136,136,46.0,90.0,1.020,NaN,NaN,NaN,normal,notpresent,notpresent,213.0,68.0,2.80,146.0,6.3,9.3,NaN,NaN,NaN,yes,yes,no,good,no,no,ckd
137,137,45.0,60.0,1.010,2.0,0.0,normal,abnormal,present,notpresent,268.0,86.0,4.00,134.0,5.1,10.0,29,9200,NaN,yes,yes,no,good,no,no,ckd
138,138,73.0,NaN,1.010,1.0,0.0,NaN,NaN,notpresent,notpresent,95.0,51.0,1.60,142.0,3.5,NaN,NaN,NaN,NaN,no,\tno,no,good,no,no,ckd
139,139,41.0,70.0,1.015,2.0,0.0,NaN,abnormal,notpresent,present,NaN,68.0,2.80,132.0,4.1,11.1,33,NaN,NaN,yes,no,no,good,yes,yes,ckd
140,140,69.0,70.0,1.010,0.0,4.0,NaN,normal,notpresent,notpresent,256.0,40.0,1.20,142.0,5.6,NaN,NaN,NaN,NaN,no,no,no,good,no,no,ckd
141,141,67.0,70.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,NaN,106.0,6.00,137.0,4.9,6.1,19,6500,NaN,yes,no,no,good,no,yes,ckd
142,142,72.0,90.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,84.0,145.0,7.10,135.0,5.3,NaN,NaN,NaN,NaN,no,yes,no,good,no,no,ckd
143,143,41.0,80.0,1.015,1.0,4.0,abnormal,normal,notpresent,notpresent,210.0,165.0,18.00,135.0,4.7,NaN,NaN,NaN,NaN,no,yes,no,good,no,no,ckd
144,144,60.0,90.0,1.010,2.0,0.0,abnormal,normal,notpresent,notpresent,105.0,53.0,2.30,136.0,5.2,11.1,33,10500,4.1,no,no,no,good,no,no,ckd
145,145,57.0,90.0,1.015,5.0,0.0,abnormal,abnormal,notpresent,present,NaN,322.0,13.00,126.0,4.8,8.0,24,4200,3.3,yes,yes,yes,poor,yes,yes,ckd
146,146,53.0,100.0,1.010,1.0,3.0,abnormal,normal,notpresent,notpresent,213.0,23.0,1.00,139.0,4.0,NaN,NaN,NaN,NaN,no,yes,no,good,no,no,ckd
147,147,60.0,60.0,1.010,3.0,1.0,normal,abnormal,present,notpresent,288.0,36.0,1.70,130.0,3.0,7.9,25,15200,3.0,yes,no,no,poor,no,yes,ckd
148,148,69.0,60.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,171.0,26.0,48.10,NaN,NaN,NaN,NaN,NaN,NaN,yes,no,no,poor,no,no,ckd
149,149,65.0,70.0,1.020,1.0,0.0,abnormal,abnormal,notpresent,notpresent,139.0,29.0,1.00,NaN,NaN,10.5,32,NaN,NaN,yes,no,no,good,yes,no,ckd
150,150,8.0,60.0,1.025,3.0,0.0,normal,normal,notpresent,notpresent,78.0,27.0,0.90,NaN,NaN,12.3,41,6700,NaN,no,no,no,poor,yes,no,ckd

BASIC DATASET INFORMATION AND OPERATIONS

In [3]:
print(Data.shape)  # 400 patients and 26 disease calculation features
print(Data.info()) # There are categorical and numerical data
print(Data.columns) # object datatype

(400, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB
None
Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [4]:
print(Data.isnull().sum())  # check for null values

print(Data['classification'].value_counts())

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64
classification
ckd       248
notckd    150
ckd\t       2
Name: count, dtype: int64

IMPUTATION-- Handling null values

In [5]:
Data.head(20)

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,notpresent,notpresent,74.0,25.0,1.1,142.0,3.2,12.2,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,NaN,normal,notpresent,notpresent,100.0,54.0,24.0,104.0,4.0,12.4,36,NaN,NaN,no,no,no,good,no,no,ckd
7,7,24.0,NaN,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,31.0,1.1,NaN,NaN,12.4,44,6900,5,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,60.0,1.9,NaN,NaN,10.8,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,107.0,7.2,114.0,3.7,9.5,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
10,10,50.0,60.0,1.010,2.0,4.0,NaN,abnormal,present,notpresent,490.0,55.0,4.0,NaN,NaN,9.4,28,NaN,NaN,yes,yes,no,good,no,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,60.0,2.7,131.0,4.2,10.8,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
12,12,68.0,70.0,1.015,3.0,1.0,NaN,normal,present,notpresent,208.0,72.0,2.1,138.0,5.8,9.7,28,12200,3.4,yes,yes,yes,poor,yes,no,ckd
13,13,68.0,70.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,98.0,86.0,4.6,135.0,3.4,9.8,NaN,NaN,NaN,yes,yes,yes,poor,yes,no,ckd
14,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,90.0,4.1,130.0,6.4,5.6,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
15,15,40.0,80.0,1.015,3.0,0.0,NaN,normal,notpresent,notpresent,76.0,162.0,9.6,141.0,4.9,7.6,24,3800,2.8,yes,no,no,good,no,yes,ckd
16,16,47.0,70.0,1.015,2.0,0.0,NaN,normal,notpresent,notpresent,99.0,46.0,2.2,138.0,4.1,12.6,NaN,NaN,NaN,no,no,no,good,no,no,ckd
17,17,47.0,80.0,NaN,NaN,NaN,NaN,NaN,notpresent,notpresent,114.0,87.0,5.2,139.0,3.7,12.1,NaN,NaN,NaN,yes,no,no,poor,no,no,ckd
18,18,60.0,100.0,1.025,0.0,3.0,NaN,normal,notpresent,notpresent,263.0,27.0,1.3,135.0,4.3,12.7,37,11400,4.3,yes,yes,yes,good,no,no,ckd
19,19,62.0,60.0,1.015,1.0,0.0,NaN,abnormal,present,notpresent,100.0,31.0,1.6,NaN,NaN,10.3,30,5300,3.7,yes,no,yes,good,no,no,ckd

In [6]:
# seperating the categorical and numerical data

num_columns = Data.select_dtypes(include=['int64','float64']).columns

cat_columns = Data.select_dtypes(include=['object']).columns

print(num_columns)
print(cat_columns)

# Missing values handling
# Numerical → median
for col in num_columns:
    Data[col].fillna(Data[col].median(), inplace=True)

# Categorical → mode
for col in cat_columns:
    Data[col].fillna(Data[col].mode()[0], inplace=True)

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot',
       'hemo'],
      dtype='object')
Index(['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [7]:
Data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,normal,normal,notpresent,notpresent,121.0,36.0,1.20,138.0,4.4,15.40,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,normal,normal,notpresent,notpresent,121.0,18.0,0.80,138.0,4.4,11.30,38,6000,5.2,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.80,138.0,4.4,9.60,31,7500,5.2,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.80,111.0,2.5,11.20,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.40,138.0,4.4,11.60,35,7300,4.6,no,no,no,good,no,no,ckd
5,5,60.0,90.0,1.015,3.0,0.0,normal,normal,notpresent,notpresent,74.0,25.0,1.10,142.0,3.2,12.20,39,7800,4.4,yes,yes,no,good,yes,no,ckd
6,6,68.0,70.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,100.0,54.0,24.00,104.0,4.0,12.40,36,9800,5.2,no,no,no,good,no,no,ckd
7,7,24.0,80.0,1.015,2.0,4.0,normal,abnormal,notpresent,notpresent,410.0,31.0,1.10,138.0,4.4,12.40,44,6900,5,no,yes,no,good,yes,no,ckd
8,8,52.0,100.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,138.0,60.0,1.90,138.0,4.4,10.80,33,9600,4.0,yes,yes,no,good,no,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,abnormal,abnormal,present,notpresent,70.0,107.0,7.20,114.0,3.7,9.50,29,12100,3.7,yes,yes,no,poor,no,yes,ckd
10,10,50.0,60.0,1.010,2.0,4.0,normal,abnormal,present,notpresent,490.0,55.0,4.00,138.0,4.4,9.40,28,9800,5.2,yes,yes,no,good,no,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,abnormal,abnormal,present,notpresent,380.0,60.0,2.70,131.0,4.2,10.80,32,4500,3.8,yes,yes,no,poor,yes,no,ckd
12,12,68.0,70.0,1.015,3.0,1.0,normal,normal,present,notpresent,208.0,72.0,2.10,138.0,5.8,9.70,28,12200,3.4,yes,yes,yes,poor,yes,no,ckd
13,13,68.0,70.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,98.0,86.0,4.60,135.0,3.4,9.80,41,9800,5.2,yes,yes,yes,poor,yes,no,ckd
14,14,68.0,80.0,1.010,3.0,2.0,normal,abnormal,present,present,157.0,90.0,4.10,130.0,6.4,5.60,16,11000,2.6,yes,yes,yes,poor,yes,no,ckd
15,15,40.0,80.0,1.015,3.0,0.0,normal,normal,notpresent,notpresent,76.0,162.0,9.60,141.0,4.9,7.60,24,3800,2.8,yes,no,no,good,no,yes,ckd
16,16,47.0,70.0,1.015,2.0,0.0,normal,normal,notpresent,notpresent,99.0,46.0,2.20,138.0,4.1,12.60,41,9800,5.2,no,no,no,good,no,no,ckd
17,17,47.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,114.0,87.0,5.20,139.0,3.7,12.10,41,9800,5.2,yes,no,no,poor,no,no,ckd
18,18,60.0,100.0,1.025,0.0,3.0,normal,normal,notpresent,notpresent,263.0,27.0,1.30,135.0,4.3,12.70,37,11400,4.3,yes,yes,yes,good,no,no,ckd
19,19,62.0,60.0,1.015,1.0,0.0,normal,abnormal,present,notpresent,100.0,31.0,1.60,138.0,4.4,10.30,30,5300,3.7,yes,no,yes,good,no,no,ckd
20,20,61.0,80.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,173.0,148.0,3.90,135.0,5.2,7.70,24,9200,3.2,yes,yes,yes,poor,yes,yes,ckd
21,21,60.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,121.0,180.0,76.00,4.5,4.4,10.90,32,6200,3.6,yes,yes,yes,good,no,no,ckd
22,22,48.0,80.0,1.025,4.0,0.0,normal,abnormal,notpresent,notpresent,95.0,163.0,7.70,136.0,3.8,9.80,32,6900,3.4,yes,no,no,good,no,yes,ckd
23,23,21.0,70.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,121.0,42.0,1.30,138.0,4.4,12.65,41,9800,5.2,no,no,no,poor,no,yes,ckd
24,24,42.0,100.0,1.015,4.0,0.0,normal,abnormal,notpresent,present,121.0,50.0,1.40,129.0,4.0,11.10,39,8300,4.6,yes,no,no,poor,no,no,ckd
25,25,61.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,108.0,75.0,1.90,141.0,5.2,9.90,29,8400,3.7,yes,yes,no,good,no,yes,ckd
26,26,75.0,80.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,156.0,45.0,2.40,140.0,3.4,11.60,35,10300,4,yes,yes,no,poor,no,no,ckd
27,27,69.0,70.0,1.010,3.0,4.0,normal,abnormal,notpresent,notpresent,264.0,87.0,2.70,130.0,4.0,12.50,37,9600,4.1,yes,yes,yes,good,yes,no,ckd
28,28,75.0,70.0,1.020,1.0,3.0,normal,normal,notpresent,notpresent,123.0,31.0,1.40,138.0,4.4,12.65,41,9800,5.2,no,yes,no,good,no,no,ckd
29,29,68.0,70.0,1.005,1.0,0.0,abnormal,abnormal,present,notpresent,121.0,28.0,1.40,138.0,4.4,12.90,38,9800,5.2,no,no,yes,good,no,no,ckd
30,30,55.0,70.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,93.0,155.0,7.30,132.0,4.9,12.65,41,9800,5.2,yes,yes,no,good,no,no,ckd
31,31,73.0,90.0,1.015,3.0,0.0,normal,abnormal,present,notpresent,107.0,33.0,1.50,141.0,4.6,10.10,30,7800,4,no,no,no,poor,no,no,ckd
32,32,61.0,90.0,1.010,1.0,1.0,normal,normal,notpresent,notpresent,159.0,39.0,1.50,133.0,4.9,11.30,34,9600,4.0,yes,yes,no,poor,no,no,ckd
33,33,60.0,100.0,1.020,2.0,0.0,abnormal,abnormal,notpresent,notpresent,140.0,55.0,2.50,138.0,4.4,10.10,29,9800,5.2,yes,no,no,poor,no,no,ckd
34,34,70.0,70.0,1.010,1.0,0.0,normal,normal,present,present,171.0,153.0,5.20,138.0,4.4,12.65,41,9800,5.2,no,yes,no,poor,no,no,ckd
35,35,65.0,90.0,1.020,2.0,1.0,abnormal,normal,notpresent,notpresent,270.0,39.0,2.00,138.0,4.4,12.00,36,9800,4.9,yes,yes,no,poor,no,yes,ckd
36,36,76.0,70.0,1.015,1.0,0.0,normal,normal,notpresent,notpresent,92.0,29.0,1.80,133.0,3.9,10.30,32,9800,5.2,yes,no,no,good,no,no,ckd
37,37,72.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,137.0,65.0,3.40,141.0,4.7,9.70,28,6900,2.5,yes,yes,no,poor,no,yes,ckd\t
38,38,69.0,80.0,1.020,3.0,0.0,abnormal,normal,notpresent,notpresent,121.0,103.0,4.10,132.0,5.9,12.50,41,9800,5.2,yes,no,no,good,no,no,ckd
39,39,82.0,80.0,1.010,2.0,2.0,normal,normal,notpresent,notpresent,140.0,70.0,3.40,136.0,4.2,13.00,40,9800,4.2,yes,yes,no,good,no,no,ckd
40,40,46.0,90.0,1.010,2.0,0.0,normal,abnormal,notpresent,notpresent,99.0,80.0,2.10,138.0,4.4,11.10,32,9100,4.1,yes,no,\tno,good,no,no,ckd
41,41,45.0,70.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,121.0,20.0,0.70,138.0,4.4,12.65,41,9800,5.2,no,no,no,good,yes,no,ckd
42,42,47.0,100.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,204.0,29.0,1.00,139.0,4.2,9.70,33,9200,4.5,yes,no,no,good,no,yes,ckd
43,43,35.0,80.0,1.010,1.0,0.0,abnormal,normal,notpresent,notpresent,79.0,202.0,10.80,134.0,3.4,7.90,24,7900,3.1,no,yes,no,good,no,no,ckd
44,44,54.0,80.0,1.010,3.0,0.0,abnormal,abnormal,notpresent,notpresent,207.0,77.0,6.30,134.0,4.8,9.70,28,9800,5.2,yes,yes,no,poor,yes,no,ckd
45,45,54.0,80.0,1.020,3.0,0.0,normal,abnormal,notpresent,notpresent,208.0,89.0,5.90,130.0,4.9,9.30,41,9800,5.2,yes,yes,no,poor,yes,no,ckd
46,46,48.0,70.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,124.0,24.0,1.20,142.0,4.2,12.40,37,6400,4.7,no,yes,no,good,no,no,ckd
47,47,11.0,80.0,1.010,3.0,0.0,normal,normal,notpresent,notpresent,121.0,17.0,0.80,138.0,4.4,15.00,45,8600,5.2,no,no,no,good,no,no,ckd
48,48,73.0,70.0,1.005,0.0,0.0,normal,normal,notpresent,notpresent,70.0,32.0,0.90,125.0,4.0,10.00,29,18900,3.5,yes,yes,no,good,yes,no,ckd
49,49,60.0,70.0,1.010,2.0,0.0,normal,abnormal,present,notpresent,144.0,72.0,3.00,138.0,4.4,9.70,29,21600,3.5,yes,yes,no,poor,no,yes,ckd
50,50,53.0,60.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,91.0,114.0,3.25,142.0,4.3,8.60,28,11000,3.8,yes,yes,no,poor,yes,yes,ckd
51,51,54.0,100.0,1.015,3.0,0.0,normal,normal,present,notpresent,162.0,66.0,1.60,136.0,4.4,10.30,33,9800,5.2,yes,yes,no,poor,yes,no,ckd
52,52,53.0,90.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,121.0,38.0,2.20,138.0,4.4,10.90,34,4300,3.7,no,no,no,poor,no,yes,ckd
53,53,62.0,80.0,1.015,0.0,5.0,normal,normal,notpresent,notpresent,246.0,24.0,1.00,138.0,4.4,13.60,40,8500,4.7,yes,yes,no,good,no,no,ckd
54,54,63.0,80.0,1.010,2.0,2.0,normal,normal,notpresent,notpresent,121.0,42.0,3.40,136.0,4.2,13.00,40,9800,4.2,yes,no,yes,good,no,no,ckd
55,55,35.0,80.0,1.005,3.0,0.0,abnormal,normal,notpresent,notpresent,121.0,42.0,1.30,138.0,4.4,9.50,28,9800,5.2,no,no,no,good,yes,no,ckd
56,56,76.0,70.0,1.015,3.0,4.0,normal,abnormal,present,notpresent,121.0,164.0,9.70,131.0,4.4,10.20,30,11300,3.4,yes,yes,yes,poor,yes,no,ckd
57,57,76.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,93.0,155.0,7.30,132.0,4.9,12.65,41,9800,5.2,yes,yes,yes,poor,no,no,ckd
58,58,73.0,80.0,1.020,2.0,0.0,abnormal,abnormal,notpresent,notpresent,253.0,142.0,4.60,138.0,5.8,10.50,33,7200,4.3,yes,yes,yes,good,no,no,ckd
59,59,59.0,100.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,121.0,96.0,6.40,138.0,4.4,6.60,41,9800,5.2,yes,yes,no,good,no,yes,ckd
60,60,67.0,90.0,1.020,1.0,0.0,normal,abnormal,present,notpresent,141.0,66.0,3.20,138.0,6.6,12.65,41,9800,5.2,yes,no,no,good,no,no,ckd
61,61,67.0,80.0,1.010,1.0,3.0,normal,abnormal,notpresent,notpresent,182.0,391.0,32.00,163.0,39.0,12.65,41,9800,5.2,no,no,no,good,yes,no,ckd
62,62,15.0,60.0,1.020,3.0,0.0,normal,normal,notpresent,notpresent,86.0,15.0,0.60,138.0,4.0,11.00,33,7700,3.8,yes,yes,no,good,no,no,ckd
63,63,46.0,70.0,1.015,1.0,0.0,abnormal,normal,notpresent,notpresent,150.0,111.0,6.10,131.0,3.7,7.50,27,9800,5.2,no,no,no,good,no,yes,ckd
64,64,55.0,80.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,146.0,42.0,1.30,138.0,4.4,9.80,41,9800,5.2,no,no,\tno,good,no,no,ckd
65,65,44.0,90.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,121.0,20.0,1.10,138.0,4.4,15.00,48,9800,5.2,no,\tno,no,good,no,no,ckd
66,66,67.0,70.0,1.020,2.0,0.0,abnormal,normal,notpresent,notpresent,150.0,55.0,1.60,131.0,4.8,12.65,\t?,9800,5.2,yes,yes,no,good,yes,no,ckd
67,67,45.0,80.0,1.020,3.0,0.0,normal,abnormal,notpresent,notpresent,425.0,42.0,1.30,138.0,4.4,12.65,41,9800,5.2,no,no,no,poor,no,no,ckd
68,68,65.0,70.0,1.010,2.0,0.0,normal,normal,present,notpresent,112.0,73.0,3.30,138.0,4.4,10.90,37,9800,5.2,no,no,no,good,no,no,ckd
69,69,26.0,70.0,1.015,0.0,4.0,normal,normal,notpresent,notpresent,250.0,20.0,1.10,138.0,4.4,15.60,52,6900,6.0,no,yes,no,good,no,no,ckd
70,70,61.0,80.0,1.015,0.0,4.0,normal,normal,notpresent,notpresent,360.0,19.0,0.70,137.0,4.4,15.20,44,8300,5.2,yes,yes,no,good,no,no,ckd
71,71,46.0,60.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,163.0,92.0,3.30,141.0,4.0,9.80,28,14600,3.2,yes,yes,no,good,no,no,ckd
72,72,64.0,90.0,1.010,3.0,3.0,normal,abnormal,present,notpresent,121.0,35.0,1.30,138.0,4.4,10.30,41,9800,5.2,yes,yes,no,good,yes,no,ckd
73,73,55.0,100.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,129.0,107.0,6.70,132.0,4.4,4.80,14,6300,5.2,yes,no,no,good,yes,yes,ckd
74,74,56.0,90.0,1.015,2.0,0.0,abnormal,abnormal,notpresent,notpresent,129.0,107.0,6.70,131.0,4.8,9.10,29,6400,3.4,yes,no,no,good,no,no,ckd
75,75,5.0,80.0,1.015,1.0,0.0,normal,normal,notpresent,notpresent,121.0,16.0,0.70,138.0,3.2,8.10,41,9800,5.2,no,no,no,good,no,yes,ckd
76,76,48.0,80.0,1.005,4.0,0.0,abnormal,abnormal,notpresent,present,133.0,139.0,8.50,132.0,5.5,10.30,36,\t6200,4,no,yes,no,good,yes,no,ckd
77,77,67.0,70.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,102.0,48.0,3.20,137.0,5.0,11.90,34,7100,3.7,yes,yes,no,good,yes,no,ckd
78,78,70.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,158.0,85.0,3.20,141.0,3.5,10.10,30,9800,5.2,yes,no,no,good,yes,no,ckd
79,79,56.0,80.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,165.0,55.0,1.80,138.0,4.4,13.50,40,11800,5.0,yes,yes,no,poor,yes,no,ckd
80,80,74.0,80.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,132.0,98.0,2.80,133.0,5.0,10.80,31,9400,3.8,yes,yes,no,good,no,no,ckd
81,81,45.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,360.0,45.0,2.40,128.0,4.4,8.30,29,5500,3.7,yes,yes,no,good,no,no,ckd
82,82,38.0,70.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,104.0,77.0,1.90,140.0,3.9,12.65,41,9800,5.2,yes,no,no,poor,yes,no,ckd
83,83,48.0,70.0,1.015,1.0,0.0,normal,normal,notpresent,notpresent,127.0,19.0,1.00,134.0,3.6,12.65,41,9800,5.2,yes,yes,no,good,no,no,ckd
84,84,59.0,70.0,1.010,3.0,0.0,normal,abnormal,notpresent,notpresent,76.0,186.0,15.00,135.0,7.6,7.10,22,3800,2.1,yes,no,no,poor,yes,yes,ckd
85,85,70.0,70.0,1.015,2.0,0.0,normal,normal,notpresent,notpresent,121.0,46.0,1.50,138.0,4.4,9.90,41,9800,5.2,no,yes,no,poor,yes,no,ckd
86,86,56.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,415.0,37.0,1.90,138.0,4.4,12.65,41,9800,5.2,no,yes,no,good,no,no,ckd
87,87,70.0,100.0,1.005,1.0,0.0,normal,abnormal,present,notpresent,169.0,47.0,2.90,138.0,4.4,11.10,32,5800,5,yes,yes,no,poor,no,no,ckd
88,88,58.0,110.0,1.010,4.0,0.0,normal,normal,notpresent,notpresent,251.0,52.0,2.20,138.0,4.4,12.65,41,13200,4.7,yes,\tyes,no,good,no,no,ckd
89,89,50.0,70.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,109.0,32.0,1.40,139.0,4.7,12.65,41,9800,5.2,no,no,no,poor,no,no,ckd
90,90,63.0,100.0,1.010,2.0,2.0,normal,normal,notpresent,present,280.0,35.0,3.20,143.0,3.5,13.00,40,9800,4.2,yes,no,yes,good,no,no,ckd
91,91,56.0,70.0,1.015,4.0,1.0,abnormal,normal,notpresent,notpresent,210.0,26.0,1.70,136.0,3.8,16.10,52,12500,5.6,no,no,no,good,no,no,ckd
92,92,71.0,70.0,1.010,3.0,0.0,normal,abnormal,present,present,219.0,82.0,3.60,133.0,4.4,10.40,33,5600,3.6,yes,yes,yes,good,no,no,ckd
93,93,73.0,100.0,1.010,3.0,2.0,abnormal,abnormal,present,notpresent,295.0,90.0,5.60,140.0,2.9,9.20,30,7000,3.2,yes,yes,yes,poor,no,no,ckd
94,94,65.0,70.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,93.0,66.0,1.60,137.0,4.5,11.60,36,11900,3.9,no,yes,no,good,no,no,ckd
95,95,62.0,90.0,1.015,1.0,0.0,normal,normal,notpresent,notpresent,94.0,25.0,1.10,131.0,3.7,12.65,41,9800,5.2,yes,no,no,good,yes,yes,ckd
96,96,60.0,80.0,1.010,1.0,1.0,normal,normal,notpresent,notpresent,172.0,32.0,2.70,138.0,4.4,11.20,36,9800,5.2,no,yes,yes,poor,no,no,ckd
97,97,65.0,60.0,1.015,1.0,0.0,normal,normal,notpresent,notpresent,91.0,51.0,2.20,132.0,3.8,10.00,32,9100,4.0,yes,yes,no,poor,yes,no,ckd
98,98,50.0,140.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,101.0,106.0,6.50,135.0,4.3,6.20,18,5800,2.3,yes,yes,no,poor,no,yes,ckd
99,99,56.0,180.0,1.020,0.0,4.0,normal,abnormal,notpresent,notpresent,298.0,24.0,1.20,139.0,3.9,11.20,32,10400,4.2,yes,yes,no,poor,yes,no,ckd
100,100,34.0,70.0,1.015,4.0,0.0,abnormal,abnormal,notpresent,notpresent,153.0,22.0,0.90,133.0,3.8,12.65,41,9800,5.2,no,no,no,good,yes,no,ckd
101,101,71.0,90.0,1.015,2.0,0.0,normal,abnormal,present,present,88.0,80.0,4.40,139.0,5.7,11.30,33,10700,3.9,no,no,no,good,no,no,ckd
102,102,17.0,60.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,92.0,32.0,2.10,141.0,4.2,13.90,52,7000,5.2,no,no,no,good,no,no,ckd
103,103,76.0,70.0,1.015,2.0,0.0,normal,abnormal,present,notpresent,226.0,217.0,10.20,138.0,4.4,10.20,36,12700,4.2,yes,no,no,poor,yes,yes,ckd
104,104,55.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,143.0,88.0,2.00,138.0,4.4,12.65,41,9800,5.2,yes,yes,no,poor,yes,no,ckd
105,105,65.0,80.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,115.0,32.0,11.50,139.0,4.0,14.10,42,6800,5.2,no,no,no,good,no,no,ckd
106,106,50.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,89.0,118.0,6.10,127.0,4.4,6.00,17,6500,5.2,yes,yes,no,good,yes,yes,ckd
107,107,55.0,100.0,1.015,1.0,4.0,normal,normal,notpresent,notpresent,297.0,53.0,2.80,139.0,4.5,11.20,34,13600,4.4,yes,yes,no,good,no,no,ckd
108,108,45.0,80.0,1.015,0.0,0.0,normal,abnormal,notpresent,notpresent,107.0,15.0,1.00,141.0,4.2,11.80,37,10200,4.2,no,no,no,good,no,no,ckd
109,109,54.0,70.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,233.0,50.1,1.90,138.0,4.4,11.70,41,9800,5.2,no,yes,no,good,no,no,ckd
110,110,63.0,90.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,123.0,19.0,2.00,142.0,3.8,11.70,34,11400,4.7,no,no,no,good,no,no,ckd
111,111,65.0,80.0,1.010,3.0,3.0,normal,normal,notpresent,notpresent,294.0,71.0,4.40,128.0,5.4,10.00,32,9000,3.9,yes,yes,yes,good,no,no,ckd
112,112,55.0,60.0,1.015,3.0,0.0,abnormal,abnormal,notpresent,notpresent,121.0,34.0,1.20,138.0,4.4,10.80,33,9800,5.2,no,no,no,good,no,no,ckd
113,113,61.0,90.0,1.015,0.0,2.0,normal,normal,notpresent,notpresent,121.0,42.0,1.30,138.0,4.4,12.65,41,9800,5.2,no,yes,no,poor,no,yes,ckd
114,114,12.0,60.0,1.015,3.0,0.0,abnormal,abnormal,present,notpresent,121.0,51.0,1.80,138.0,4.4,12.10,41,10300,5.2,no,no,no,good,no,no,ckd
115,115,47.0,80.0,1.010,0.0,0.0,normal,abnormal,notpresent,notpresent,121.0,28.0,0.90,138.0,4.4,12.40,44,5600,4.3,no,no,no,good,no,yes,ckd
116,116,55.0,70.0,1.015,4.0,0.0,abnormal,normal,notpresent,notpresent,104.0,16.0,0.50,138.0,4.4,12.65,41,9800,5.2,no,no,no,good,yes,no,ckd
117,117,55.0,70.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,219.0,36.0,1.30,139.0,3.7,12.50,37,9800,4.4,no,no,no,good,no,no,ckd
118,118,55.0,70.0,1.010,3.0,0.0,normal,normal,notpresent,notpresent,99.0,25.0,1.20,138.0,4.4,11.40,41,9800,5.2,no,no,no,poor,yes,no,ckd
119,119,60.0,70.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,140.0,27.0,1.20,138.0,4.4,12.65,41,9800,5.2,no,no,no,good,no,no,ckd
120,120,72.0,90.0,1.025,1.0,3.0,normal,normal,notpresent,notpresent,323.0,40.0,2.20,137.0,5.3,12.60,41,9800,5.2,no,yes,yes,poor,no,no,ckd
121,121,54.0,60.0,1.020,3.0,0.0,normal,normal,notpresent,notpresent,125.0,21.0,1.30,137.0,3.4,15.00,46,9800,5.2,yes,yes,no,good,yes,no,ckd
122,122,34.0,70.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,121.0,219.0,12.20,130.0,3.8,6.00,41,9800,5.2,yes,no,no,good,no,yes,ckd
123,123,43.0,80.0,1.015,2.0,3.0,normal,abnormal,present,present,121.0,30.0,1.10,138.0,4.4,14.00,42,14900,5.2,no,no,no,good,no,no,ckd
124,124,65.0,100.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,90.0,98.0,2.50,138.0,4.4,9.10,28,5500,3.6,yes,no,no,good,no,no,ckd
125,125,72.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,308.0,36.0,2.50,131.0,4.3,12.65,41,9800,5.2,yes,yes,no,poor,no,no,ckd
126,126,70.0,90.0,1.015,0.0,0.0,normal,normal,notpresent,notpresent,144.0,125.0,4.00,136.0,4.6,12.00,37,8200,4.5,yes,yes,no,poor,yes,no,ckd
127,127,71.0,60.0,1.015,4.0,0.0,normal,normal,notpresent,notpresent,118.0,125.0,5.30,136.0,4.9,11.40,35,15200,4.3,yes,yes,no,poor,yes,no,ckd
128,128,52.0,90.0,1.015,4.0,3.0,normal,abnormal,notpresent,notpresent,224.0,166.0,5.60,133.0,47.0,8.10,23,5000,2.9,yes,yes,no,good,no,yes,ckd
129,129,75.0,70.0,1.025,1.0,0.0,normal,normal,notpresent,notpresent,158.0,49.0,1.40,135.0,4.7,11.10,41,9800,5.2,yes,no,no,poor,yes,no,ckd
130,130,50.0,90.0,1.010,2.0,0.0,normal,abnormal,present,present,128.0,208.0,9.20,134.0,4.8,8.20,22,16300,2.7,no,no,no,poor,yes,yes,ckd
131,131,5.0,50.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,121.0,25.0,0.60,138.0,4.4,11.80,36,12400,5.2,no,no,no,good,no,no,ckd
132,132,50.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,219.0,176.0,13.80,136.0,4.5,8.60,24,13200,2.7,yes,no,no,good,yes,yes,ckd
133,133,70.0,100.0,1.015,4.0,0.0,normal,normal,notpresent,notpresent,118.0,125.0,5.30,136.0,4.9,12.00,37,\t8400,8.0,yes,no,no,good,no,no,ckd
134,134,47.0,100.0,1.010,0.0,0.0,normal,normal,notpresent,notpresent,122.0,42.0,16.90,138.0,5.2,10.80,33,10200,3.8,no,yes,no,good,no,no,ckd
135,135,48.0,80.0,1.015,0.0,2.0,normal,normal,notpresent,notpresent,214.0,24.0,1.30,140.0,4.0,13.20,39,9800,5.2,no,yes,no,poor,no,no,ckd
136,136,46.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,213.0,68.0,2.80,146.0,6.3,9.30,41,9800,5.2,yes,yes,no,good,no,no,ckd
137,137,45.0,60.0,1.010,2.0,0.0,normal,abnormal,present,notpresent,268.0,86.0,4.00,134.0,5.1,10.00,29,9200,5.2,yes,yes,no,good,no,no,ckd
138,138,73.0,80.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,95.0,51.0,1.60,142.0,3.5,12.65,41,9800,5.2,no,\tno,no,good,no,no,ckd
139,139,41.0,70.0,1.015,2.0,0.0,normal,abnormal,notpresent,present,121.0,68.0,2.80,132.0,4.1,11.10,33,9800,5.2,yes,no,no,good,yes,yes,ckd
140,140,69.0,70.0,1.010,0.0,4.0,normal,normal,notpresent,notpresent,256.0,40.0,1.20,142.0,5.6,12.65,41,9800,5.2,no,no,no,good,no,no,ckd
141,141,67.0,70.0,1.010,1.0,0.0,normal,normal,notpresent,notpresent,121.0,106.0,6.00,137.0,4.9,6.10,19,6500,5.2,yes,no,no,good,no,yes,ckd
142,142,72.0,90.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,84.0,145.0,7.10,135.0,5.3,12.65,41,9800,5.2,no,yes,no,good,no,no,ckd
143,143,41.0,80.0,1.015,1.0,4.0,abnormal,normal,notpresent,notpresent,210.0,165.0,18.00,135.0,4.7,12.65,41,9800,5.2,no,yes,no,good,no,no,ckd
144,144,60.0,90.0,1.010,2.0,0.0,abnormal,normal,notpresent,notpresent,105.0,53.0,2.30,136.0,5.2,11.10,33,10500,4.1,no,no,no,good,no,no,ckd

ENCODING THE TARGET VARIABLE AND CAT COLUMNS

In [8]:
# Target variable--Classification Column encoding using LabelEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Data['classification'] = le.fit_transform(Data['classification']) #for Target variable


#Categrical data is converted to numerical using LabelEncoder
Data['rbc'] = le.fit_transform(Data['rbc'])
Data['pc'] = le.fit_transform(Data['pc'])
Data['pcc'] = le.fit_transform(Data['pcc'])
Data['ba'] = le.fit_transform(Data['ba'])
Data['htn'] = le.fit_transform(Data['htn'])
Data['dm'] = le.fit_transform(Data['cad'])
Data['appet'] = le.fit_transform(Data['appet'])
Data['pe'] = le.fit_transform(Data['pe'])
Data['pcv'] = le.fit_transform(Data['pcv'])
Data['wc'] = le.fit_transform(Data['wc'])
Data['rc'] = le.fit_transform(Data['rc'])
Data['cad'] = le.fit_transform(Data['cad'])
Data['ane'] = le.fit_transform(Data['ane'])


Data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,1,1,0,0,121.0,36.0,1.2,138.0,4.4,15.4,32,72,34,1,1,1,0,0,0,0
1,1,7.0,50.0,1.020,4.0,0.0,1,1,0,0,121.0,18.0,0.8,138.0,4.4,11.3,26,56,34,0,1,1,0,0,0,0
2,2,62.0,80.0,1.010,2.0,3.0,1,1,0,0,423.0,53.0,1.8,138.0,4.4,9.6,19,70,34,0,1,1,1,0,1,0
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,117.0,56.0,3.8,111.0,2.5,11.2,20,62,19,1,1,1,1,1,1,0
4,4,51.0,80.0,1.010,2.0,0.0,1,1,0,0,106.0,26.0,1.4,138.0,4.4,11.6,23,68,27,0,1,1,0,0,0,0

In [9]:
Data.dtypes

id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                 int32
pc                  int32
pcc                 int32
ba                  int32
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv                 int32
wc                  int32
rc                  int32
htn                 int32
dm                  int32
cad                 int32
appet               int32
pe                  int32
ane                 int32
classification      int32
dtype: object

OUTLIERS DETECTION AND REMOVAL

In [10]:
print(Data.head())
print(Data.columns)
print(num_columns)

   id   age    bp     sg   al   su  rbc  pc  pcc  ba    bgr    bu   sc    sod  \
0   0  48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.0  36.0  1.2  138.0
1   1   7.0  50.0  1.020  4.0  0.0    1   1    0   0  121.0  18.0  0.8  138.0
2   2  62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.0  53.0  1.8  138.0
3   3  48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.0  56.0  3.8  111.0
4   4  51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.0  26.0  1.4  138.0

   pot  hemo  pcv  wc  rc  htn  dm  cad  appet  pe  ane  classification
0  4.4  15.4   32  72  34    1   1    1      0   0    0               0
1  4.4  11.3   26  56  34    0   1    1      0   0    0               0
2  4.4   9.6   19  70  34    0   1    1      1   0    1               0
3  2.5  11.2   20  62  19    1   1    1      1   1    1               0
4  4.4  11.6   23  68  27    0   1    1      0   0    0               0
Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')
Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot',
       'hemo'],
      dtype='object')

In [11]:
# Outliers detection using IQR and removing outliers using IQR

Q1 = Data[num_columns].quantile(0.25)
Q3 = Data[num_columns].quantile(0.75)
IQR = Q3 - Q1

outliers = ((Data[num_columns] < (Q1 - 1.5 * IQR)) | 
            (Data[num_columns] > (Q3 + 1.5 * IQR)))


outliers.sum()

for col in num_columns:
    Q1 = Data[col].quantile(0.25)
    Q3 = Data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    Data[col] = Data[col].clip(lower, upper)

Data.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.0200,1.0,0.0,1,1,0,0,121.0,36.0,1.2,138.0,4.4,15.4,32,72,34,1,1,1,0,0,0,0
1,1,9.0,55.0,1.0200,4.0,0.0,1,1,0,0,121.0,18.0,0.8,138.0,4.4,11.3,26,56,34,0,1,1,0,0,0,0
2,2,62.0,80.0,1.0100,2.0,0.0,1,1,0,0,223.5,53.0,1.8,138.0,4.4,9.6,19,70,34,0,1,1,1,0,1,0
3,3,48.0,70.0,1.0075,4.0,0.0,1,0,1,0,117.0,56.0,3.8,126.0,2.8,11.2,20,62,19,1,1,1,1,1,1,0
4,4,51.0,80.0,1.0100,2.0,0.0,1,1,0,0,106.0,26.0,1.4,138.0,4.4,11.6,23,68,27,0,1,1,0,0,0,0

In [39]:
outliers.sum()

id       0
age     10
bp      36
sg       7
al       0
su      61
bgr     53
bu      41
sc      53
sod     18
pot     14
hemo     2
dtype: int64

SEPERATING THE FEATURES AND TARGET

In [13]:
X = Data.drop('classification', axis=1)
Y = Data['classification']

In [14]:
X

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,0,48.0,80.0,1.0200,1.0,0.0,1,1,0,0,121.0,36.000,1.2000,138.0,4.4,15.40,32,72,34,1,1,1,0,0,0
1,1,9.0,55.0,1.0200,4.0,0.0,1,1,0,0,121.0,18.000,0.8000,138.0,4.4,11.30,26,56,34,0,1,1,0,0,0
2,2,62.0,80.0,1.0100,2.0,0.0,1,1,0,0,223.5,53.000,1.8000,138.0,4.4,9.60,19,70,34,0,1,1,1,0,1
3,3,48.0,70.0,1.0075,4.0,0.0,1,0,1,0,117.0,56.000,3.8000,126.0,2.8,11.20,20,62,19,1,1,1,1,1,1
4,4,51.0,80.0,1.0100,2.0,0.0,1,1,0,0,106.0,26.000,1.4000,138.0,4.4,11.60,23,68,27,0,1,1,0,0,0
5,5,60.0,90.0,1.0150,3.0,0.0,1,1,0,0,74.0,25.000,1.1000,142.0,3.2,12.20,27,72,25,1,1,1,0,1,0
6,6,68.0,70.0,1.0100,0.0,0.0,1,1,0,0,100.0,54.000,5.4625,126.0,4.0,12.40,24,90,34,0,1,1,0,0,0
7,7,24.0,80.0,1.0150,2.0,0.0,1,0,0,0,223.5,31.000,1.1000,138.0,4.4,12.40,32,64,31,0,1,1,0,1,0
8,8,52.0,95.0,1.0150,3.0,0.0,1,0,1,0,138.0,60.000,1.9000,138.0,4.4,10.80,21,88,21,1,1,1,0,0,1
9,9,53.0,90.0,1.0200,2.0,0.0,0,0,1,0,70.0,107.000,5.4625,126.0,3.7,9.50,17,18,17,1,1,1,1,0,1
10,10,50.0,60.0,1.0100,2.0,0.0,1,0,1,0,223.5,55.000,4.0000,138.0,4.4,9.40,16,90,34,1,1,1,0,0,1
11,11,63.0,70.0,1.0100,3.0,0.0,0,0,1,0,223.5,60.000,2.7000,131.0,4.2,10.80,20,43,18,1,1,1,1,1,0
12,12,68.0,70.0,1.0150,3.0,0.0,1,1,1,0,208.0,72.000,2.1000,138.0,5.8,9.70,16,19,14,1,2,2,1,1,0
13,13,68.0,70.0,1.0200,0.0,0.0,1,1,0,0,98.0,86.000,4.6000,135.0,3.4,9.80,29,90,34,1,2,2,1,1,0
14,14,68.0,80.0,1.0100,3.0,0.0,1,0,1,1,157.0,90.000,4.1000,130.0,6.0,5.60,4,10,5,1,2,2,1,1,0
15,15,40.0,80.0,1.0150,3.0,0.0,1,1,0,0,76.0,113.875,5.4625,141.0,4.9,7.60,12,39,7,1,1,1,0,0,1
16,16,47.0,70.0,1.0150,2.0,0.0,1,1,0,0,99.0,46.000,2.2000,138.0,4.1,12.60,29,90,34,0,1,1,0,0,0
17,17,47.0,80.0,1.0200,0.0,0.0,1,1,0,0,114.0,87.000,5.2000,139.0,3.7,12.10,29,90,34,1,1,1,1,0,0
18,18,60.0,95.0,1.0250,0.0,0.0,1,1,0,0,223.5,27.000,1.3000,135.0,4.3,12.70,25,13,24,1,2,2,0,0,0
19,19,62.0,60.0,1.0150,1.0,0.0,1,0,1,0,100.0,31.000,1.6000,138.0,4.4,10.30,18,49,17,1,2,2,0,0,0
20,20,61.0,80.0,1.0150,2.0,0.0,0,0,0,0,173.0,113.875,3.9000,135.0,5.2,7.70,12,84,12,1,2,2,1,1,1
21,21,60.0,90.0,1.0200,0.0,0.0,1,1,0,0,121.0,113.875,5.4625,126.0,4.4,10.90,20,57,16,1,2,2,0,0,0
22,22,48.0,80.0,1.0250,4.0,0.0,1,0,0,0,95.0,113.875,5.4625,136.0,3.8,9.80,20,64,14,1,1,1,0,0,1
23,23,21.0,70.0,1.0100,0.0,0.0,1,1,0,0,121.0,42.000,1.3000,138.0,4.4,12.65,29,90,34,0,1,1,1,0,1
24,24,42.0,95.0,1.0150,4.0,0.0,1,0,0,1,121.0,50.000,1.4000,129.0,4.0,11.10,27,77,27,1,1,1,1,0,0
25,25,61.0,60.0,1.0250,0.0,0.0,1,1,0,0,108.0,75.000,1.9000,141.0,5.2,9.90,17,78,17,1,1,1,0,0,1
26,26,75.0,80.0,1.0150,0.0,0.0,1,1,0,0,156.0,45.000,2.4000,140.0,3.4,11.60,23,4,20,1,1,1,1,0,0
27,27,69.0,70.0,1.0100,3.0,0.0,1,0,0,0,223.5,87.000,2.7000,130.0,4.0,12.50,25,88,22,1,2,2,0,1,0
28,28,75.0,70.0,1.0200,1.0,0.0,1,1,0,0,123.0,31.000,1.4000,138.0,4.4,12.65,29,90,34,0,1,1,0,0,0
29,29,68.0,70.0,1.0075,1.0,0.0,0,0,1,0,121.0,28.000,1.4000,138.0,4.4,12.90,26,90,34,0,2,2,0,0,0
30,30,55.0,70.0,1.0200,0.0,0.0,1,1,0,0,93.0,113.875,5.4625,132.0,4.9,12.65,29,90,34,1,1,1,0,0,0
31,31,73.0,90.0,1.0150,3.0,0.0,1,0,1,0,107.0,33.000,1.5000,141.0,4.6,10.10,18,72,20,0,1,1,1,0,0
32,32,61.0,90.0,1.0100,1.0,0.0,1,1,0,0,159.0,39.000,1.5000,133.0,4.9,11.30,22,88,21,1,1,1,1,0,0
33,33,60.0,95.0,1.0200,2.0,0.0,0,0,0,0,140.0,55.000,2.5000,138.0,4.4,10.10,17,90,34,1,1,1,1,0,0
34,34,70.0,70.0,1.0100,1.0,0.0,1,1,1,1,171.0,113.875,5.2000,138.0,4.4,12.65,29,90,34,0,1,1,1,0,0
35,35,65.0,90.0,1.0200,2.0,0.0,0,1,0,0,223.5,39.000,2.0000,138.0,4.4,12.00,24,90,30,1,1,1,1,0,1
36,36,76.0,70.0,1.0150,1.0,0.0,1,1,0,0,92.0,29.000,1.8000,133.0,3.9,10.30,20,90,34,1,1,1,0,0,0
37,37,72.0,80.0,1.0200,0.0,0.0,1,1,0,0,137.0,65.000,3.4000,141.0,4.7,9.70,16,64,4,1,1,1,1,0,1
38,38,69.0,80.0,1.0200,3.0,0.0,0,1,0,0,121.0,103.000,4.1000,132.0,5.9,12.50,29,90,34,1,1,1,0,0,0
39,39,82.0,80.0,1.0100,2.0,0.0,1,1,0,0,140.0,70.000,3.4000,136.0,4.2,13.00,28,90,23,1,1,1,0,0,0
40,40,46.0,90.0,1.0100,2.0,0.0,1,0,0,0,99.0,80.000,2.1000,138.0,4.4,11.10,20,83,22,1,0,0,0,0,0
41,41,45.0,70.0,1.0100,0.0,0.0,1,1,0,0,121.0,20.000,0.7000,138.0,4.4,12.65,29,90,34,0,1,1,0,1,0
42,42,47.0,95.0,1.0100,0.0,0.0,1,1,0,0,204.0,29.000,1.0000,139.0,4.2,9.70,21,84,26,1,1,1,0,0,1
43,43,35.0,80.0,1.0100,1.0,0.0,0,1,0,0,79.0,113.875,5.4625,134.0,3.4,7.90,12,73,11,0,1,1,0,0,0
44,44,54.0,80.0,1.0100,3.0,0.0,0,0,0,0,207.0,77.000,5.4625,134.0,4.8,9.70,16,90,34,1,1,1,1,1,0
45,45,54.0,80.0,1.0200,3.0,0.0,1,0,0,0,208.0,89.000,5.4625,130.0,4.9,9.30,29,90,34,1,1,1,1,1,0
46,46,48.0,70.0,1.0150,0.0,0.0,1,1,0,0,124.0,24.000,1.2000,142.0,4.2,12.40,25,59,28,0,1,1,0,0,0
47,47,11.0,80.0,1.0100,3.0,0.0,1,1,0,0,121.0,17.000,0.8000,138.0,4.4,15.00,33,80,34,0,1,1,0,0,0
48,48,73.0,70.0,1.0075,0.0,0.0,1,1,0,0,70.0,32.000,0.9000,126.0,4.0,10.00,17,33,15,1,1,1,0,1,0
49,49,60.0,70.0,1.0100,2.0,0.0,1,0,1,0,144.0,72.000,3.0000,138.0,4.4,9.70,17,35,15,1,1,1,1,0,1
50,50,53.0,60.0,1.0200,0.0,0.0,1,1,0,0,91.0,113.875,3.2500,142.0,4.3,8.60,16,10,18,1,1,1,1,1,1
51,51,54.0,95.0,1.0150,3.0,0.0,1,1,1,0,162.0,66.000,1.6000,136.0,4.4,10.30,21,90,34,1,1,1,1,1,0
52,52,53.0,90.0,1.0150,0.0,0.0,1,1,0,0,121.0,38.000,2.2000,138.0,4.4,10.90,22,42,17,0,1,1,1,0,1
53,53,62.0,80.0,1.0150,0.0,0.0,1,1,0,0,223.5,24.000,1.0000,138.0,4.4,13.60,28,79,28,1,1,1,0,0,0
54,54,63.0,80.0,1.0100,2.0,0.0,1,1,0,0,121.0,42.000,3.4000,136.0,4.2,13.00,28,90,23,1,2,2,0,0,0
55,55,35.0,80.0,1.0075,3.0,0.0,0,1,0,0,121.0,42.000,1.3000,138.0,4.4,9.50,16,90,34,0,1,1,0,1,0
56,56,76.0,70.0,1.0150,3.0,0.0,1,0,1,0,121.0,113.875,5.4625,131.0,4.4,10.20,18,12,14,1,2,2,1,1,0
57,57,76.0,90.0,1.0200,0.0,0.0,1,1,0,0,93.0,113.875,5.4625,132.0,4.9,12.65,29,90,34,1,2,2,1,0,0
58,58,73.0,80.0,1.0200,2.0,0.0,0,0,0,0,223.5,113.875,4.6000,138.0,5.8,10.50,21,67,24,1,2,2,0,0,0
59,59,59.0,95.0,1.0200,0.0,0.0,1,1,0,0,121.0,96.000,5.4625,138.0,4.4,6.60,29,90,34,1,1,1,0,0,1
60,60,67.0,90.0,1.0200,1.0,0.0,1,0,1,0,141.0,66.000,3.2000,138.0,6.0,12.65,29,90,34,1,1,1,0,0,0
61,61,67.0,80.0,1.0100,1.0,0.0,1,0,0,0,182.0,113.875,5.4625,150.0,6.0,12.65,29,90,34,0,1,1,0,1,0
62,62,15.0,60.0,1.0200,3.0,0.0,1,1,0,0,86.0,15.000,0.6000,138.0,4.0,11.00,21,71,18,1,1,1,0,0,0
63,63,46.0,70.0,1.0150,1.0,0.0,0,1,0,0,150.0,111.000,5.4625,131.0,3.7,7.50,15,90,34,0,1,1,0,0,1
64,64,55.0,80.0,1.0100,0.0,0.0,1,1,0,0,146.0,42.000,1.3000,138.0,4.4,9.80,29,90,34,0,0,0,0,0,0
65,65,44.0,90.0,1.0100,1.0,0.0,1,1,0,0,121.0,20.000,1.1000,138.0,4.4,15.00,36,90,34,0,1,1,0,0,0
66,66,67.0,70.0,1.0200,2.0,0.0,0,1,0,0,150.0,55.000,1.6000,131.0,4.8,12.65,1,90,34,1,1,1,0,1,0
67,67,45.0,80.0,1.0200,3.0,0.0,1,0,0,0,223.5,42.000,1.3000,138.0,4.4,12.65,29,90,34,0,1,1,1,0,0
68,68,65.0,70.0,1.0100,2.0,0.0,1,1,1,0,112.0,73.000,3.3000,138.0,4.4,10.90,25,90,34,0,1,1,0,0,0
69,69,26.0,70.0,1.0150,0.0,0.0,1,1,0,0,223.5,20.000,1.1000,138.0,4.4,15.60,40,64,42,0,1,1,0,0,0
70,70,61.0,80.0,1.0150,0.0,0.0,1,1,0,0,223.5,19.000,0.7000,137.0,4.4,15.20,32,77,34,1,1,1,0,0,0
71,71,46.0,60.0,1.0100,1.0,0.0,1,1,0,0,163.0,92.000,3.3000,141.0,4.0,9.80,16,27,12,1,1,1,0,0,0
72,72,64.0,90.0,1.0100,3.0,0.0,1,0,1,0,121.0,35.000,1.3000,138.0,4.4,10.30,29,90,34,1,1,1,0,1,0
73,73,55.0,95.0,1.0150,2.0,0.0,0,0,0,0,129.0,107.000,5.4625,132.0,4.4,5.25,2,58,34,1,1,1,0,1,1
74,74,56.0,90.0,1.0150,2.0,0.0,0,0,0,0,129.0,107.000,5.4625,131.0,4.8,9.10,17,59,14,1,1,1,0,0,0
75,75,9.0,80.0,1.0150,1.0,0.0,1,1,0,0,121.0,16.000,0.7000,138.0,3.2,8.10,29,90,34,0,1,1,0,0,1
76,76,48.0,80.0,1.0075,4.0,0.0,0,0,0,1,133.0,113.875,5.4625,132.0,5.5,10.30,24,0,20,0,1,1,0,1,0
77,77,67.0,70.0,1.0100,1.0,0.0,1,1,0,0,102.0,48.000,3.2000,137.0,5.0,11.90,22,66,17,1,1,1,0,1,0
78,78,70.0,80.0,1.0200,0.0,0.0,1,1,0,0,158.0,85.000,3.2000,141.0,3.5,10.10,18,90,34,1,1,1,0,1,0
79,79,56.0,80.0,1.0100,1.0,0.0,1,1,0,0,165.0,55.000,1.8000,138.0,4.4,13.50,28,15,32,1,1,1,1,1,0
80,80,74.0,80.0,1.0100,0.0,0.0,1,1,0,0,132.0,98.000,2.8000,133.0,5.0,10.80,19,86,18,1,1,1,0,0,0
81,81,45.0,90.0,1.0200,0.0,0.0,1,1,0,0,223.5,45.000,2.4000,128.0,4.4,8.30,17,51,17,1,1,1,0,0,0
82,82,38.0,70.0,1.0200,0.0,0.0,1,1,0,0,104.0,77.000,1.9000,140.0,3.9,12.65,29,90,34,1,1,1,1,1,0
83,83,48.0,70.0,1.0150,1.0,0.0,1,1,0,0,127.0,19.000,1.0000,134.0,3.6,12.65,29,90,34,1,1,1,0,0,0
84,84,59.0,70.0,1.0100,3.0,0.0,1,0,0,0,76.0,113.875,5.4625,135.0,6.0,7.10,10,39,1,1,1,1,1,1,1
85,85,70.0,70.0,1.0150,2.0,0.0,1,1,0,0,121.0,46.000,1.5000,138.0,4.4,9.90,29,90,34,0,1,1,1,1,0
86,86,56.0,80.0,1.0200,0.0,0.0,1,1,0,0,223.5,37.000,1.9000,138.0,4.4,12.65,29,90,34,0,1,1,0,0,0
87,87,70.0,95.0,1.0075,1.0,0.0,1,0,1,0,169.0,47.000,2.9000,138.0,4.4,11.10,20,54,31,1,1,1,1,0,0
88,88,58.0,95.0,1.0100,4.0,0.0,1,1,0,0,223.5,52.000,2.2000,138.0,4.4,12.65,29,25,28,1,1,1,0,0,0
89,89,50.0,70.0,1.0200,0.0,0.0,1,1,0,0,109.0,32.000,1.4000,139.0,4.7,12.65,29,90,34,0,1,1,1,0,0
90,90,63.0,95.0,1.0100,2.0,0.0,1,1,0,1,223.5,35.000,3.2000,143.0,3.5,13.00,28,90,23,1,2,2,0,0,0
91,91,56.0,70.0,1.0150,4.0,0.0,0,1,0,0,210.0,26.000,1.7000,136.0,3.8,16.10,40,22,38,0,1,1,0,0,0
92,92,71.0,70.0,1.0100,3.0,0.0,1,0,1,1,219.0,82.000,3.6000,133.0,4.4,10.40,21,52,16,1,2,2,0,0,0
93,93,73.0,95.0,1.0100,3.0,0.0,0,0,1,0,223.5,90.000,5.4625,140.0,2.9,9.20,18,65,12,1,2,2,1,0,0
94,94,65.0,70.0,1.0100,0.0,0.0,1,1,0,0,93.0,66.000,1.6000,137.0,4.5,11.60,24,16,19,0,1,1,0,0,0
95,95,62.0,90.0,1.0150,1.0,0.0,1,1,0,0,94.0,25.000,1.1000,131.0,3.7,12.65,29,90,34,1,1,1,0,1,1
96,96,60.0,80.0,1.0100,1.0,0.0,1,1,0,0,172.0,32.000,2.7000,138.0,4.4,11.20,24,90,34,0,2,2,1,0,0
97,97,65.0,60.0,1.0150,1.0,0.0,1,1,0,0,91.0,51.000,2.2000,132.0,3.8,10.00,20,83,21,1,1,1,1,1,0
98,98,50.0,95.0,1.0200,0.0,0.0,1,1,0,0,101.0,106.000,5.4625,135.0,4.3,6.20,6,54,2,1,1,1,1,0,1
99,99,56.0,95.0,1.0200,0.0,0.0,1,0,0,0,223.5,24.000,1.2000,139.0,3.9,11.20,20,5,23,1,1,1,1,1,0
100,100,34.0,70.0,1.0150,4.0,0.0,0,0,0,0,153.0,22.000,0.9000,133.0,3.8,12.65,29,90,34,0,1,1,0,1,0
101,101,71.0,90.0,1.0150,2.0,0.0,1,0,1,1,88.0,80.000,4.4000,139.0,5.7,11.30,21,7,19,0,1,1,0,0,0
102,102,17.0,60.0,1.0100,0.0,0.0,1,1,0,0,92.0,32.000,2.1000,141.0,4.2,13.90,40,65,34,0,1,1,0,0,0
103,103,76.0,70.0,1.0150,2.0,0.0,1,0,1,0,223.5,113.875,5.4625,138.0,4.4,10.20,24,23,23,1,1,1,1,1,1
104,104,55.0,90.0,1.0200,0.0,0.0,1,1,0,0,143.0,88.000,2.0000,138.0,4.4,12.65,29,90,34,1,1,1,1,1,0
105,105,65.0,80.0,1.0150,0.0,0.0,1,1,0,0,115.0,32.000,5.4625,139.0,4.0,14.10,30,63,34,0,1,1,0,0,0
106,106,50.0,90.0,1.0200,0.0,0.0,1,1,0,0,89.0,113.875,5.4625,127.0,4.4,6.00,5,60,34,1,1,1,0,1,1
107,107,55.0,95.0,1.0150,1.0,0.0,1,1,0,0,223.5,53.000,2.8000,139.0,4.5,11.20,22,26,25,1,1,1,0,0,0
108,108,45.0,80.0,1.0150,0.0,0.0,1,0,0,0,107.0,15.000,1.0000,141.0,4.2,11.80,25,3,23,0,1,1,0,0,0
109,109,54.0,70.0,1.0200,0.0,0.0,1,1,0,0,223.5,50.100,1.9000,138.0,4.4,11.70,29,90,34,0,1,1,0,0,0
110,110,63.0,90.0,1.0150,0.0,0.0,1,1,0,0,123.0,19.000,2.0000,142.0,3.8,11.70,22,13,28,0,1,1,0,0,0
111,111,65.0,80.0,1.0100,3.0,0.0,1,1,0,0,223.5,71.000,4.4000,128.0,5.4,10.00,20,82,19,1,2,2,0,0,0
112,112,55.0,60.0,1.0150,3.0,0.0,0,0,0,0,121.0,34.000,1.2000,138.0,4.4,10.80,21,90,34,0,1,1,0,0,0
113,113,61.0,90.0,1.0150,0.0,0.0,1,1,0,0,121.0,42.000,1.3000,138.0,4.4,12.65,29,90,34,0,1,1,1,0,1
114,114,12.0,60.0,1.0150,3.0,0.0,0,0,1,0,121.0,51.000,1.8000,138.0,4.4,12.10,29,4,34,0,1,1,0,0,0
115,115,47.0,80.0,1.0100,0.0,0.0,1,0,0,0,121.0,28.000,0.9000,138.0,4.4,12.40,32,52,24,0,1,1,0,0,1
116,116,55.0,70.0,1.0150,4.0,0.0,0,1,0,0,104.0,16.000,0.5000,138.0,4.4,12.65,29,90,34,0,1,1,0,1,0
117,117,55.0,70.0,1.0200,0.0,0.0,1,1,0,0,219.0,36.000,1.3000,139.0,3.7,12.50,25,90,25,0,1,1,0,0,0
118,118,55.0,70.0,1.0100,3.0,0.0,1,1,0,0,99.0,25.000,1.2000,138.0,4.4,11.40,29,90,34,0,1,1,1,1,0
119,119,60.0,70.0,1.0100,0.0,0.0,1,1,0,0,140.0,27.000,1.2000,138.0,4.4,12.65,29,90,34,0,1,1,0,0,0
120,120,72.0,90.0,1.0250,1.0,0.0,1,1,0,0,223.5,40.000,2.2000,137.0,5.3,12.60,29,90,34,0,2,2,1,0,0
121,121,54.0,60.0,1.0200,3.0,0.0,1,1,0,0,125.0,21.000,1.3000,137.0,3.4,15.00,34,90,34,1,1,1,0,1,0
122,122,34.0,70.0,1.0200,0.0,0.0,1,1,0,0,121.0,113.875,5.4625,130.0,3.8,6.00,29,90,34,1,1,1,0,0,1
123,123,43.0,80.0,1.0150,2.0,0.0,1,0,1,1,121.0,30.000,1.1000,138.0,4.4,14.00,30,28,34,0,1,1,0,0,0
124,124,65.0,95.0,1.0150,0.0,0.0,1,1,0,0,90.0,98.000,2.5000,138.0,4.4,9.10,16,51,16,1,1,1,0,0,0
125,125,72.0,90.0,1.0200,0.0,0.0,1,1,0,0,223.5,36.000,2.5000,131.0,4.3,12.65,29,90,34,1,1,1,1,0,0
126,126,70.0,90.0,1.0150,0.0,0.0,1,1,0,0,144.0,113.875,4.0000,136.0,4.6,12.00,25,76,26,1,1,1,1,1,0
127,127,71.0,60.0,1.0150,4.0,0.0,1,1,0,0,118.0,113.875,5.3000,136.0,4.9,11.40,23,29,24,1,1,1,1,1,0
128,128,52.0,90.0,1.0150,4.0,0.0,1,0,0,0,223.5,113.875,5.4625,133.0,6.0,8.10,11,46,8,1,1,1,0,0,1
129,129,75.0,70.0,1.0250,1.0,0.0,1,1,0,0,158.0,49.000,1.4000,135.0,4.7,11.10,29,90,34,1,1,1,1,1,0
130,130,50.0,90.0,1.0100,2.0,0.0,1,0,1,1,128.0,113.875,5.4625,134.0,4.8,8.20,10,31,6,0,1,1,1,1,1
131,131,9.0,55.0,1.0100,0.0,0.0,1,1,0,0,121.0,25.000,0.6000,138.0,4.4,11.80,24,21,34,0,1,1,0,0,0
132,132,50.0,80.0,1.0200,0.0,0.0,1,1,0,0,219.0,113.875,5.4625,136.0,4.5,8.60,12,25,6,1,1,1,0,1,1
133,133,70.0,95.0,1.0150,4.0,0.0,1,1,0,0,118.0,113.875,5.3000,136.0,4.9,12.00,25,1,48,1,1,1,0,0,0
134,134,47.0,95.0,1.0100,0.0,0.0,1,1,0,0,122.0,42.000,5.4625,138.0,5.2,10.80,21,3,18,0,1,1,0,0,0
135,135,48.0,80.0,1.0150,0.0,0.0,1,1,0,0,214.0,24.000,1.3000,140.0,4.0,13.20,27,90,34,0,1,1,1,0,0
136,136,46.0,90.0,1.0200,0.0,0.0,1,1,0,0,213.0,68.000,2.8000,146.0,6.0,9.30,29,90,34,1,1,1,0,0,0
137,137,45.0,60.0,1.0100,2.0,0.0,1,0,1,0,223.5,86.000,4.0000,134.0,5.1,10.00,17,84,34,1,1,1,0,0,0
138,138,73.0,80.0,1.0100,1.0,0.0,1,1,0,0,95.0,51.000,1.6000,142.0,3.5,12.65,29,90,34,0,1,1,0,0,0
139,139,41.0,70.0,1.0150,2.0,0.0,1,0,0,1,121.0,68.000,2.8000,132.0,4.1,11.10,21,90,34,1,1,1,0,1,1
140,140,69.0,70.0,1.0100,0.0,0.0,1,1,0,0,223.5,40.000,1.2000,142.0,5.6,12.65,29,90,34,0,1,1,0,0,0
141,141,67.0,70.0,1.0100,1.0,0.0,1,1,0,0,121.0,106.000,5.4625,137.0,4.9,6.10,7,60,34,1,1,1,0,0,1
142,142,72.0,90.0,1.0200,0.0,0.0,1,1,0,0,84.0,113.875,5.4625,135.0,5.3,12.65,29,90,34,0,1,1,0,0,0
143,143,41.0,80.0,1.0150,1.0,0.0,0,1,0,0,210.0,113.875,5.4625,135.0,4.7,12.65,29,90,34,0,1,1,0,0,0
144,144,60.0,90.0,1.0100,2.0,0.0,0,1,0,0,105.0,53.000,2.3000,136.0,5.2,11.10,21,6,22,0,1,1,0,0,0
145,145,57.0,90.0,1.0150,5.0,0.0,0,0,0,1,121.0,113.875,5.4625,126.0,4.8,8.00,12,41,13,1,2,2,1,1,1
146,146,53.0,95.0,1.0100,1.0,0.0,0,1,0,0,213.0,23.000,1.0000,139.0,4.0,12.65,29,90,34,0,1,1,0,0,0
147,147,60.0,60.0,1.0100,3.0,0.0,1,0,1,0,223.5,36.000,1.7000,130.0,3.0,7.90,13,29,10,1,1,1,1,0,1
148,148,69.0,60.0,1.0200,0.0,0.0,1,1,0,0,171.0,26.000,5.4625,138.0,4.4,12.65,29,90,34,1,1,1,1,0,0
149,149,65.0,70.0,1.0200,1.0,0.0,0,0,0,0,139.0,29.000,1.0000,138.0,4.4,10.50,20,90,34,1,1,1,0,1,0
150,150,9.0,60.0,1.0250,3.0,0.0,1,1,0,0,78.0,27.000,0.9000,138.0,4.4,12.30,29,62,34,0,1,1,1,1,0
151,151,76.0,90.0,1.0200,0.0,0.0,1,1,0,0,172.0,46.000,1.7000,141.0,5.5,9.60,18,90,34,1,1,1,0,0,1
152,152,39.0,70.0,1.0100,0.0,0.0,1,1,0,0,121.0,20.000,0.8000,133.0,3.5,10.90,20,90,34,0,1,1,0,0,0
153,153,55.0,90.0,1.0100,2.0,0.0,0,0,0,0,223.5,113.875,5.4625,132.0,3.4,8.30,10,27,8,1,1,1,1,1,1
154,154,56.0,90.0,1.0075,4.0,0.0,0,0,0,0,223.5,113.875,5.4625,140.0,4.2,8.40,14,90,9,1,1,1,1,1,1
155,155,50.0,70.0,1.0200,3.0,0.0,0,1,1,1,123.0,40.000,1.8000,138.0,4.4,11.10,24,44,34,0,1,1,0,0,0
156,156,66.0,90.0,1.0150,2.0,0.0,1,1,0,1,153.0,76.000,3.3000,138.0,4.4,12.65,29,90,34,0,1,1,1,0,0
157,157,62.0,70.0,1.0250,3.0,0.0,1,0,0,0,122.0,42.000,1.7000,136.0,4.7,12.60,27,73,19,1,1,1,0,0,0
158,158,71.0,60.0,1.0200,3.0,0.0,1,1,1,0,223.5,48.000,1.5000,132.0,4.0,10.90,19,90,34,1,2,2,0,0,0
159,159,59.0,80.0,1.0100,1.0,0.0,0,1,0,0,223.5,35.000,1.3000,126.0,3.5,10.40,23,9,24,0,1,1,1,0,0
160,160,81.0,60.0,1.0200,0.0,0.0,1,1,0,0,148.0,39.000,2.1000,147.0,4.2,10.90,23,86,3,1,2,2,1,1,0
161,161,62.0,80.0,1.0150,3.0,0.0,0,1,0,0,121.0,42.000,1.3000,138.0,4.4,14.30,30,3,29,1,1,1,0,0,0
162,162,59.0,70.0,1.0200,0.0,0.0,1,1,0,0,204.0,34.000,1.5000,126.0,4.1,9.80,25,56,0,0,1,1,0,0,0
163,163,46.0,80.0,1.0100,0.0,0.0,1,1,0,0,160.0,40.000,2.0000,140.0,4.1,9.00,15,75,12,1,1,1,1,0,1
164,164,14.0,80.0,1.0150,0.0,0.0,1,1,0,0,192.0,15.000,0.8000,137.0,4.2,14.30,28,87,36,0,1,1,1,1,0
165,165,60.0,80.0,1.0200,0.0,0.0,1,1,0,0,121.0,42.000,1.3000,138.0,4.4,12.65,29,90,34,0,1,1,0,0,0
166,166,27.0,60.0,1.0200,0.0,0.0,1,1,0,0,76.0,44.000,3.9000,127.0,4.3,12.65,29,90,34,0,1,1,1,1,1
167,167,34.0,70.0,1.0200,0.0,0.0,0,1,0,0,139.0,19.000,0.9000,138.0,4.4,12.70,30,36,34,0,1,1,1,0,0
168,168,65.0,70.0,1.0150,4.0,0.0,1,1,1,0,223.5,28.000,1.5000,138.0,4.4,11.00,27,62,34,1,1,1,0,0,0
169,169,55.0,70.0,1.0100,0.0,0.0,1,1,0,0,220.0,68.000,2.8000,138.0,4.4,8.70,15,90,34,1,1,1,0,0,1
170,170,66.0,70.0,1.0150,2.0,0.0,1,1,0,0,223.5,41.000,1.7000,131.0,3.9,12.50,21,88,25,1,1,1,0,0,0
171,171,83.0,70.0,1.0200,3.0,0.0,1,1,0,0,102.0,60.000,2.6000,126.0,5.7,8.70,14,24,11,1,1,1,1,0,1
172,172,62.0,80.0,1.0100,1.0,0.0,1,1,0,0,223.5,113.000,2.9000,130.0,2.8,10.60,22,24,30,0,1,1,0,0,0
173,173,17.0,70.0,1.0150,1.0,0.0,0,1,0,0,27.5,1.500,5.4625,145.0,2.8,13.10,29,11,34,0,1,1,0,0,0
174,174,54.0,70.0,1.0200,0.0,0.0,1,1,0,0,111.0,113.875,5.4625,141.0,4.7,11.00,23,80,27,0,1,1,0,0,0
175,175,60.0,55.0,1.0100,0.0,0.0,1,1,0,0,223.5,58.000,2.2000,126.0,3.0,12.65,29,41,14,1,1,1,0,0,0
176,176,21.0,90.0,1.0100,4.0,0.0,1,0,1,1,107.0,40.000,1.7000,126.0,3.5,8.30,11,21,19,0,1,1,0,0,1
177,177,65.0,80.0,1.0150,2.0,0.0,1,1,1,0,215.0,113.875,2.5000,138.0,4.4,13.20,29,90,34,0,1,1,0,0,0
178,178,42.0,90.0,1.0200,2.0,0.0,0,0,1,0,93.0,113.875,2.7000,139.0,4.3,9.80,22,90,34,0,1,1,1,1,1
179,179,72.0,90.0,1.0100,2.0,0.0,1,0,1,0,124.0,53.000,2.3000,138.0,4.4,11.90,27,90,34,0,1,1,0,0,0
180,180,73.0,90.0,1.0100,1.0,0.0,0,0,1,0,223.5,56.000,1.9000,138.0,4.4,10.30,16,90,34,0,1,1,0,0,0
181,181,45.0,70.0,1.0250,2.0,0.0,1,0,1,0,117.0,52.000,2.2000,136.0,3.8,10.00,18,34,17,0,1,1,0,0,0
182,182,61.0,80.0,1.0200,0.0,0.0,1,1,0,0,131.0,23.000,0.8000,140.0,4.1,11.30,23,90,34,0,1,1,0,0,0
183,183,30.0,70.0,1.0150,0.0,0.0,1,1,0,0,101.0,106.000,5.4625,135.0,4.3,12.65,29,90,34,0,1,1,1,0,0
184,184,54.0,60.0,1.0150,3.0,0.0,1,0,0,0,223.5,113.875,3.3000,133.0,4.5,11.30,19,54,16,1,2,2,1,1,0
185,185,9.0,80.0,1.0200,1.0,0.0,1,1,0,0,99.0,23.000,0.6000,138.0,4.4,12.00,22,2,34,0,1,1,0,0,0
186,186,9.0,55.0,1.0200,4.0,0.0,1,1,0,0,121.0,46.000,1.0000,135.0,3.8,12.65,29,90,34,0,1,1,0,1,0
187,187,9.0,80.0,1.0100,2.0,0.0,1,1,0,0,121.0,22.000,0.7000,138.0,4.4,10.70,22,20,34,0,1,1,0,0,0
188,188,9.0,80.0,1.0200,0.0,0.0,1,1,0,0,80.0,66.000,2.5000,142.0,3.6,12.20,26,90,34,0,1,1,0,0,0
189,189,64.0,60.0,1.0100,4.0,0.0,0,0,0,1,223.5,58.000,4.3000,137.0,5.4,9.50,17,70,14,1,1,1,1,1,0
190,190,9.0,60.0,1.0100,4.0,0.0,0,0,0,1,94.0,67.000,1.0000,135.0,4.9,9.90,18,32,29,0,1,1,1,0,0
191,191,55.0,70.0,1.0100,3.0,0.0,1,1,0,0,110.0,113.875,5.4625,134.0,2.8,9.10,14,84,14,1,1,1,1,0,0
192,192,46.0,95.0,1.0150,0.0,0.0,1,1,0,0,130.0,16.000,0.9000,138.0,4.4,12.65,29,90,34,0,1,1,0,0,0
193,193,32.0,90.0,1.0250,1.0,0.0,0,0,0,0,121.0,113.875,5.4625,126.0,6.0,5.50,3,37,7,1,1,1,1,1,1
194,194,80.0,70.0,1.0100,2.0,0.0,1,0,0,0,121.0,49.000,1.2000,138.0,4.4,12.65,29,90,34,1,1,1,0,0,0
195,195,70.0,90.0,1.0200,2.0,0.0,0,0,0,1,184.0,98.600,3.3000,138.0,3.9,5.80,29,90,34,1,2,2,1,0,0
196,196,49.0,95.0,1.0100,3.0,0.0,0,0,0,0,129.0,113.875,5.4625,126.0,3.2,8.10,12,88,15,1,1,1,1,1,1
197,197,57.0,80.0,1.0200,0.0,0.0,1,1,0,0,121.0,111.000,5.4625,126.0,5.3,6.80,29,42,10,1,1,1,0,0,1
198,198,59.0,95.0,1.0200,4.0,0.0,1,1,0,0,223.5,40.000,3.2000,137.0,4.7,11.20,18,38,19,1,1,1,1,1,0
199,199,65.0,80.0,1.0150,0.0,0.0,1,1,0,0,92.0,37.000,1.5000,140.0,5.2,8.80,13,7,12,1,2,2,0,1,0
200,200,90.0,90.0,1.0250,1.0,0.0,1,1,0,0,139.0,89.000,3.0000,140.0,4.1,12.00,25,73,19,1,1,1,0,0,0
201,201,64.0,70.0,1.0200,0.0,0.0,1,1,0,0,113.0,94.000,5.4625,137.0,4.3,7.90,9,90,34,1,2,2,0,1,1
202,202,78.0,60.0,1.0200,0.0,0.0,1,1,0,0,114.0,74.000,2.9000,135.0,5.9,8.00,12,90,34,0,1,1,0,0,1
203,203,55.0,90.0,1.0200,0.0,0.0,1,1,0,0,207.0,80.000,5.4625,142.0,5.5,8.50,29,90,34,1,1,1,0,0,1
204,204,65.0,90.0,1.0100,4.0,0.0,1,1,0,0,172.0,82.000,5.4625,145.0,6.0,8.80,19,90,34,1,1,1,0,1,1
205,205,61.0,70.0,1.0200,0.0,0.0,1,1,0,0,100.0,28.000,2.1000,138.0,4.4,12.60,31,90,34,1,1,1,0,0,0

In [15]:
Y

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     0
78     0
79     0
80     0
81     0
82     0
83     0
84     0
85     0
86     0
87     0
88     0
89     0
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    0
161    0
162    0
163    0
164    0
165    0
166    0
167    0
168    0
169    0
170    0
171    0
172    0
173    0
174    0
175    0
176    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0
184    0
185    0
186    0
187    0
188    0
189    0
190    0
191    0
192    0
193    0
194    0
195    0
196    0
197    0
198    0
199    0
200    0
201    0
202    0
203    0
204    0
205    0
206    0
207    0
208    0
209    0
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    0
218    0
219    0
220    0
221    0
222    0
223    0
224    0
225    0
226    0
227    0
228    0
229    0
230    1
231    0
232    0
233    0
234    0
235    0
236    0
237    0
238    0
239    0
240    0
241    0
242    0
243    0
244    0
245    0
246    0
247    0
248    0
249    0
250    2
251    2
252    2
253    2
254    2
255    2
256    2
257    2
258    2
259    2
260    2
261    2
262    2
263    2
264    2
265    2
266    2
267    2
268    2
269    2
270    2
271    2
272    2
273    2
274    2
275    2
276    2
277    2
278    2
279    2
280    2
281    2
282    2
283    2
284    2
285    2
286    2
287    2
288    2
289    2
290    2
291    2
292    2
293    2
294    2
295    2
296    2
297    2
298    2
299    2
300    2
301    2
302    2
303    2
304    2
305    2
306    2
307    2
308    2
309    2
310    2
311    2
312    2
313    2
314    2
315    2
316    2
317    2
318    2
319    2
320    2
321    2
322    2
323    2
324    2
325    2
326    2
327    2
328    2
329    2
330    2
331    2
332    2
333    2
334    2
335    2
336    2
337    2
338    2
339    2
340    2
341    2
342    2
343    2
344    2
345    2
346    2
347    2
348    2
349    2
350    2
351    2
352    2
353    2
354    2
355    2
356    2
357    2
358    2
359    2
360    2
361    2
362    2
363    2
364    2
365    2
366    2
367    2
368    2
369    2
370    2
371    2
372    2
373    2
374    2
375    2
376    2
377    2
378    2
379    2
380    2
381    2
382    2
383    2
384    2
385    2
386    2
387    2
388    2
389    2
390    2
391    2
392    2
393    2
394    2
395    2
396    2
397    2
398    2
399    2
Name: classification, dtype: int32

TRAIN AND TEST SPLIT

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=45,stratify=Y)

In [17]:
X_train.shape

(320, 25)

In [18]:
Y_train.shape

(320,)

In [19]:
X_test.shape

(80, 25)

In [20]:
Y_test.shape

(80,)

In [21]:
feature_names = X_train.columns
feature_names

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane'],
      dtype='object')

FEATURE SCALING - STANDARDIZATION

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled)
print(X_test_scaled)

[[ 1.017551    0.54661008 -0.51063436 ... -0.50487816 -0.4951123
  -0.42521972]
 [-1.40019682 -0.29722629  1.72776285 ... -0.50487816 -0.4951123
   2.35172538]
 [ 0.95623131  0.24523994 -1.40599325 ... -0.50487816 -0.4951123
  -0.42521972]
 ...
 [-0.94467911  0.78770618 -0.51063436 ... -0.50487816 -0.4951123
  -0.42521972]
 [ 0.49195365 -0.59859642  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 [-0.0949634   0.18496592 -0.51063436 ...  1.98067588 -0.4951123
  -0.42521972]]
[[ 1.41174901  0.90825423  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 [ 1.65702777 -0.96024058  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 [ 0.10651559  0.96852826  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]
 ...
 [-0.69940035 -1.08078864 -0.51063436 ... -0.50487816 -0.4951123
   2.35172538]
 [-1.63671563 -0.71914448  0.38472452 ... -0.50487816 -0.4951123
   2.35172538]
 [ 0.43063395 -1.74380293  0.38472452 ... -0.50487816 -0.4951123
  -0.42521972]]

DIMENSIONALITY REDUCTION ---PRINCIPAL COMPONENT ANALYSIS

In [23]:
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)   # 95% variance

X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)
print(X_train_pca)
print(X_test_pca)

[[-3.13674169 -0.53035348  0.35472891 ... -0.26380792 -0.44820023
  -0.41875094]
 [ 1.49613047  0.97474167 -1.72690312 ...  0.42269017 -0.03522404
  -0.55064148]
 [-2.98296275 -0.59008697 -0.11738637 ...  0.40938898  0.39568746
   0.11296495]
 ...
 [ 0.10573218  0.37019135 -0.2192586  ... -0.78708264 -0.10444817
  -0.24814117]
 [-2.49307682  0.15323774  0.2597103  ... -0.13270848  0.10155322
   0.1031579 ]
 [ 3.36199854  0.81428278 -1.03884323 ...  0.14869636 -0.81540459
   1.52666268]]
[[-2.79880179 -0.57111005 -0.18394585 ... -0.58544794 -0.31746267
   0.20655631]
 [-3.44272335 -0.11417733  0.36139045 ...  0.43114577  0.43143024
   0.39902982]
 [ 0.43051059  0.32353142  0.25096336 ... -1.42721585  1.60462496
   0.23022096]
 ...
 [ 2.03199356  1.07929726 -2.26661419 ...  1.32228981  0.4211985
  -0.8481531 ]
 [ 3.77853117  1.41446378 -1.91014507 ...  1.86506108 -1.38043718
   0.51261574]
 [-3.55964589 -0.02953858 -0.02296169 ...  0.57944786 -0.82083275
  -0.58152673]]

SCALING THE DATA FOR NON-NEG VALUES FOR CHI2 ANALYSIS

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_data = scaler.fit_transform(X_train_pca)
X_test_data = scaler.transform(X_test_pca)
print(X_train_data)
print(X_test_data)

[[0.06045171 0.42826182 0.47323922 ... 0.43822504 0.37840386 0.3892208 ]
 [0.44228642 0.5667856  0.21591237 ... 0.57506782 0.47945105 0.3556155 ]
 [0.07312595 0.42276415 0.41487735 ... 0.57241643 0.58488665 0.52470035]
 ...
 [0.32769178 0.51114487 0.40228413 ... 0.33391831 0.46251326 0.43269164]
 [0.11350165 0.49117721 0.46149323 ... 0.46435768 0.51291777 0.52220154]
 [0.5960686  0.55201752 0.30096885 ... 0.52045139 0.28855614 0.88490611]]
[[0.08830423 0.42451073 0.40664941 ... 0.37411107 0.41039278 0.54854714]
 [0.03523313 0.46656524 0.47406271 ... 0.57675331 0.59363221 0.59758878]
 [0.35445955 0.50685045 0.46041195 ... 0.20631765 0.88069    0.55457682]
 ...
 [0.48645149 0.57640854 0.14919446 ... 0.7543891  0.59112871 0.27981047]
 [0.63039863 0.60725611 0.1932604  ... 0.86258216 0.15030372 0.62653012]
 [0.02559654 0.4743551  0.42654993 ... 0.60631504 0.28722797 0.34774604]]

FEATURE SELECTION- SELECTKBEST , CHI2

In [25]:
from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(score_func=chi2, k=10)

X_train_selected = selector.fit_transform(X_train_data, Y_train)
X_test_selected = selector.transform(X_test_data)

In [26]:
print(X_train_selected)
print(X_test_selected )

[[0.06045171 0.42826182 0.30941769 ... 0.36846078 0.50331842 0.57234494]
 [0.44228642 0.5667856  0.19667529 ... 0.41872857 0.64717055 0.52316984]
 [0.07312595 0.42276415 0.40159904 ... 0.4702894  0.52747379 0.49740634]
 ...
 [0.32769178 0.51114487 0.51179291 ... 0.78955533 0.44414729 0.54310063]
 [0.11350165 0.49117721 0.29816774 ... 0.52583916 0.53689693 0.4982983 ]
 [0.5960686  0.55201752 0.2666119  ... 0.56141012 0.30066521 0.32681949]]
[[ 0.08830423  0.42451073  0.4835393   0.50512206  0.29471406  0.45870881
   0.33340081  0.46907288  0.5521265   0.60931099]
 [ 0.03523313  0.46656524  0.50189949  0.39710417  0.36382019  0.54077857
   0.38531566  0.4407769   0.49723727  0.49446468]
 [ 0.35445955  0.50685045  0.38805854  0.35481508  0.59152719  0.56741362
   0.25771186  0.54836255  0.69156431  0.48445782]
 [ 0.14942508  0.47707541  0.43892303  0.42656847  0.58610759  0.43469697
   0.43046463  0.43513055  0.44259803  0.52967784]
 [ 0.56977235  0.54159958  0.22572851  0.71097036  0.9375124   0.31794714
   0.21516307  0.38350972  0.36241003  0.31905752]
 [ 0.22845132  0.59251661  0.23177478  0.19403311  0.85869515  0.48952596
   0.57579947  0.48051967  0.33059605  0.4481934 ]
 [ 0.43213391  0.47555449  0.16688007  0.44264925  0.31234603  0.31701259
   0.45099614  0.59126476  0.69754018  0.35628977]
 [ 0.47544458  0.52667787  0.17329883  0.34404622  0.6183114   0.60095286
   0.57265351  0.56182729  0.30787397  0.68369316]
 [ 0.18365668  0.47521363  0.41195251  0.38530608  0.5726874   0.48983176
   0.39610975  0.41776392  0.50073759  0.63020233]
 [ 0.39056124  0.54194069  0.22622768  0.39630787  0.48640237  0.00795964
   0.50609376  0.66681131  0.3376243   0.63955037]
 [ 0.21655531  0.47939195  0.26579337  0.33868843  0.47972175  0.51283181
   0.40974179  0.57266341  0.58820892  0.56527922]
 [ 0.09247922  0.42058834  0.45556914  0.57409311  0.47217122  0.47321823
   0.35568786  0.55574148  0.65026199  0.59594686]
 [ 0.58208116  0.51061843  0.46146851  0.8047289   0.53623273  0.15764454
   0.51093273  0.57599801  0.28346265  0.4721554 ]
 [ 0.82707379  0.20682858  0.89797325  0.24847449  0.58069213  0.40058985
   0.0807996   0.56056692  0.36086084  0.64937812]
 [ 0.27696231  0.48538049  0.03388662  0.57927148  0.5066528   0.31734267
   0.42736411  0.40773268  0.7130649   0.56559787]
 [ 0.13002997  0.45871814  0.49957935  0.43090782  0.53548215  0.50205933
   0.36806381  0.41093598  0.46244205  0.52477246]
 [ 0.36603068  0.49761061  0.13033199  0.3874192   0.51860028  0.24977752
   0.40006521  0.69191966  0.63421839  0.76928795]
 [ 0.21457257  0.49584741  0.22304483  0.40033667  0.6043975   0.36957488
   0.46654986  0.67463223  0.57072098  0.60064774]
 [ 0.08560182  0.43695671  0.3508404   0.52063589  0.5670758   0.45532561
   0.37423965  0.71005703  0.5913839   0.61960199]
 [ 0.09611148  0.5042142   0.58575073  0.31293277  0.3127561   0.52480003
   0.4221421   0.49996313  0.40417939  0.31601334]
 [ 0.04978256  0.4703147   0.55329136  0.5519723   0.73214597  0.49793398
   0.43240551  0.43940395  0.46799236  0.40113948]
 [ 0.73138884  0.5906874   0.14075633  0.61639229  0.56911148  0.54997883
   0.12262731  0.52332994  0.26159816  0.57768278]
 [ 0.07225298  0.49222565  0.52290514  0.37322018  0.39728845  0.48878676
   0.44991026  0.42876981  0.3845156   0.35026827]
 [ 0.56208398  0.63688049  0.53088201  0.08133248  0.31674633  0.02223212
   0.34898643  0.75349798  0.32433836  0.345476  ]
 [ 0.05726133  0.45336584  0.48969552  0.53269362  0.54743431  0.43139795
   0.36577201  0.44129404  0.45041723  0.53721115]
 [ 0.61708991  0.11132436  0.50745801  0.46495237  0.46049231  0.31637975
   0.36714458  0.58569114  0.76353561  0.45159744]
 [ 0.3909131   0.46015923  0.09509128  0.43651222  0.31583505  0.60389813
   0.43369534  0.2444248   0.23379715  0.67871915]
 [ 0.08508152  0.4799875   0.51409835  0.38139376  0.63247672  0.60236151
   0.42414073  0.3692395   0.4182897   0.45626895]
 [ 0.13177993  0.47237947  0.57076623  0.45793006  0.51556439  0.44806649
   0.40704266  0.43110698  0.50096231  0.59643371]
 [ 0.26695906  0.47311292  0.19743379  0.42497499  0.62409009  0.42430329
   0.3725559   0.28010255  0.37548903  0.44458662]
 [ 0.45711681  0.10827307  0.17753517  0.26087369  0.61023343  0.58947456
   0.54827041  0.63882169  0.12623795  0.5204672 ]
 [ 0.43051027  0.56208255  0.39841386  0.21241515  0.47399535  0.10841431
   0.20697731  0.27176243  0.09776427  0.31681494]
 [ 0.54823027  0.54167596  0.65691172  0.76397193  0.39488205  0.51720487
   0.47629595  0.6954686   0.4640363   0.50137338]
 [ 0.06119018  0.48532733  0.44857806  0.49892741  0.61063452  0.40401343
   0.3752863   0.30310037  0.45597056  0.54296029]
 [ 0.51378305  0.53484717  0.25589938  0.29247779  0.68664157  0.22043959
   0.14635139  0.44619502  0.6921643   0.82273622]
 [ 0.69171835  0.10597688  0.51904566  0.21402808  0.74138741  0.30490785
  -0.05753869  0.43084113  0.3437314   0.38285868]
 [ 0.64403125  0.5340732   0.65781064  0.5244034   0.44412021  0.47074045
   0.39401493  0.23793921  0.66746269  0.26570385]
 [ 0.05739818  0.43665471  0.48064614  0.57857307  0.54890752  0.46772365
   0.35456774  0.52678377  0.52541965  0.45769113]
 [ 0.00983244  0.44579057  0.60276609  0.62169393  0.62714259  0.43724656
   0.38071107  0.43155683  0.44996464  0.42346296]
 [ 0.401919    0.51124612  0.26907629  0.48270541  0.22854769  0.35931015
   0.54132696  0.60985174  0.10714485  0.42154723]
 [ 0.27056199  0.47116395  0.28478541  0.30530432  0.06415236  0.43727477
   0.32235238  0.32116406  0.41207202  0.43409243]
 [ 0.65814311  0.1005899   0.30546967  0.23583121  0.8864158   0.25736477
   0.39836515  0.2907512   0.38156256  0.49612696]
 [ 0.59264116  0.56744821  0.54231516  0.47201072  0.57140138  0.21850761
   0.35506696  0.62173261  0.57347764  0.50871034]
 [ 0.51698638  0.55388842  0.29210913  0.60647728  0.54840961  0.83010533
   0.38124642  1.00808445  0.34722886  0.56751744]
 [ 0.23951929  0.50351119  0.16611474  0.3781673   0.65985286  0.37612734
   0.47165619  0.61752239  0.47798328  0.55702328]
 [ 0.57052858  0.58296116  0.30790874  0.3321367   0.33154301  0.55488537
   0.86774693  0.25673922  0.48692905  0.75613548]
 [ 0.10662002  0.46117459  0.59890418  0.5356651   0.66652251  0.45035405
   0.35433008  0.5064022   0.44124037  0.55498382]
 [ 0.53752724  0.10840936  0.46076995  0.16669772  0.61953556  0.45768781
  -0.03677954  0.36073961  0.43110696  0.3954975 ]
 [ 0.10884534  0.49101667  0.29508016  0.50384037  0.47404137  0.29374857
   0.40929902  0.42277096  0.47087845  0.572874  ]
 [ 0.72697842  0.07732794  0.41116232  0.66260962  0.99223026  0.70401196
   0.4259002   0.67641495  0.19569538  0.57315495]
 [ 0.05178931  0.50083669  0.43038212  0.35516597  0.29889957  0.48785064
   0.45661791  0.45786537  0.47413319  0.48440791]
 [ 0.15801661  0.45646675  0.41804339  0.51360609  0.42801893  0.36627466
   0.38832374  0.51813949  0.55386342  0.51911456]
 [ 0.15713612  0.45520665  0.45560382  0.46725014  0.53771855  0.49350225
   0.40726511  0.36605089  0.5581388   0.45837838]
 [ 0.10286876  0.45989377  0.44239517  0.42428979  0.43537078  0.49902862
   0.39051815  0.44063439  0.41261947  0.50056299]
 [ 0.56776354  0.5417807   0.18963947  0.54601573  0.45053067  0.76185544
   0.37716183  0.8182537   0.24602532  0.47285604]
 [ 0.56021679  0.53890539  0.78493135  0.55019748  0.45390175  0.27200465
   0.35124257  0.31262866  0.52977053  0.580344  ]
 [ 0.13871862  0.47494283  0.29261161  0.37115057  0.30538409  0.45276294
   0.40362446  0.44444849  0.51568805  0.59390129]
 [ 0.26567121  0.54721953  0.15708317  0.41469286  0.65199881  0.74866913
   0.66532065  0.27647657  0.27921345  0.4242939 ]
 [ 0.46675027  0.56984284  0.28284797  0.1878093   0.26188246  0.49248405
   0.24200413  0.25764126  0.05665546  0.74638867]
 [ 0.15424722  0.5088964   0.16075563  0.33179125  0.77073147  0.51383851
   0.44311481  0.21308805  0.20638561  0.43132699]
 [ 0.10706694  0.46874072  0.41778735  0.36864883  0.63735108  0.66305593
   0.43929501  0.57741036  0.58797835  0.37621862]
 [ 0.51504868  0.65258805  0.68656976  0.34645412  0.68618914  0.37227361
   0.62663977  0.27516295  0.28299208  0.70281716]
 [ 0.32070673  0.55743003  0.12162664 -0.02748297  0.43095994  0.53332042
   0.23558026  0.42621891  0.37255882  0.5122407 ]
 [ 0.9939978   0.14254729  0.71054083  0.60160385  0.86464502  0.57030199
   0.81503709  0.6313164   0.48341097  0.69057053]
 [ 0.07572011  0.45096991  0.42565718  0.45877778  0.20569875  0.45836169
   0.36688161  0.35543443  0.53107498  0.57209489]
 [ 0.54731552  0.06666597  0.43204682  0.40254568  0.32505792  0.28091563
   0.49389618  0.73004279  0.07543881  0.5882717 ]
 [ 0.60286485  0.56748755  0.43928987  0.46569156  0.76393942  0.49719844
   0.45252086  0.52392179  0.72962031  0.31964963]
 [ 0.48766227  0.0976274   0.20623997  0.19664114  0.62226909  0.3190706
   0.46727358  0.68915485  0.46853399  0.50368201]
 [ 0.04566162  0.40790215  0.33013588  0.64966973  0.25720359  0.3188792
   0.27599721  0.36548684  0.47766211  0.56603054]
 [ 0.05983105  0.47022988  0.47351378  0.45154934  0.64643937  0.54420877
   0.38044915  0.25644586  0.37885358  0.48728929]
 [ 0.50379349  0.56151694  0.34318916  0.43492934  0.4233068   0.79969017
   0.50883754  0.50019397  0.49925208  0.53388853]
 [ 0.58890809  0.60314014  0.31014044  0.49471697  0.56386726  0.78596959
   0.2398387   0.69298602  0.65684163  0.48279299]
 [ 0.45963538  0.50548349  0.52773601  0.27200782  0.38405153  0.35453867
   0.47347747  0.7653169   0.60134808  0.44666551]
 [ 0.14342465  0.47082167  0.40626684  0.38497039  0.35865139  0.48459656
   0.412576    0.46997748  0.47879102  0.48591058]
 [ 0.26584771  0.56565442  0.25097621  0.53821904  0.78126376  0.29092344
   0.51251849  0.23443896  0.56116541  0.39784865]
 [ 0.10511738  0.43950753  0.43333796  0.45471476  0.33931962  0.52234695
   0.37742773  0.50607137  0.51190313  0.34507793]
 [ 0.21448055  0.48038443  0.31078546  0.3846059   0.49209484  0.42736035
   0.42205363  0.56365473  0.50688701  0.56089316]
 [ 0.48645149  0.57640854  0.46462625  0.49473693  0.33888039  0.18296467
   0.37634895  0.29398483  0.44867467  0.44807148]
 [ 0.63039863  0.60725611  0.76700358  0.39438463  0.61394468  0.35899931
   0.44328664  0.70182345  0.55368711  0.36628209]
 [ 0.02559654  0.4743551   0.48947225  0.4125025   0.52856114  0.59505792
   0.47342415  0.60428754  0.46673387  0.32681991]]

In [27]:
X_train_selected.shape

(320, 10)

In [28]:
X_test_selected .shape

(80, 10)

BEST SELECTED K FEATURES

feature_scores = pd.DataFrame({
    'Feature': feature_names,
    'Chi2_score': selector.scores_
})

feature_sorted = feature_scores.sort_values(
    by='Chi2_score',
    ascending=False
)

print(feature_sorted)


print(len(feature_names))
print(len(selector.scores_))

selected_features = feature_names[selector.get_support()]
print("Selected Features:", list(selected_features))

APPLYING KNN ALGORITHM AND EVALUATION

In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [30]:
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)

knn.fit(X_train_selected, Y_train)

y_pred = knn.predict(X_test_selected)
print(y_pred)

[2 2 0 2 0 0 0 0 2 0 0 2 0 0 0 2 0 0 2 2 2 0 2 0 2 0 0 2 2 0 0 0 0 2 0 0 0
 2 2 0 2 0 0 0 0 0 2 0 2 0 2 2 2 2 0 0 2 0 0 0 2 0 0 0 2 0 0 0 2 2 0 0 0 2
 0 2 0 0 0 2]

In [31]:
accuracy = accuracy_score(Y_test, y_pred)
print("KNN Accuracy:", accuracy)

print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred))
      
print("Classification Report:\n", classification_report(Y_test, y_pred))

KNN Accuracy: 0.9875
Confusion Matrix:
 [[49  1]
 [ 0 30]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

DECISION TREE ALG AND EVALUATION

In [32]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(criterion='gini',max_depth=5,random_state=42)


decision_tree.fit(X_train_selected, Y_train)

y_pred_dt = decision_tree.predict(X_test_selected)

print(y_pred_dt)

[2 2 0 2 0 0 0 0 0 0 0 2 0 0 0 2 0 0 2 2 2 0 2 0 2 0 0 2 2 0 0 0 0 2 0 0 0
 2 2 0 0 0 0 0 0 0 2 0 2 0 2 2 2 2 0 0 2 0 0 0 2 0 0 0 2 0 0 0 2 2 0 0 0 2
 0 2 0 0 0 2]

In [33]:

print("Decision Tree Accuracy:", accuracy_score(Y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_dt))
print("Classification Report:\n", classification_report(Y_test, y_pred_dt))

Decision Tree Accuracy: 0.9875
Confusion Matrix:
 [[50  0]
 [ 1 29]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        50
           2       1.00      0.97      0.98        30

    accuracy                           0.99        80
   macro avg       0.99      0.98      0.99        80
weighted avg       0.99      0.99      0.99        80

NAIVE BAYES ALG- (Gaussian, multinomial and bernoullis) AND EVALUATION

In [34]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train_selected, Y_train)
y_pred_nb = nb.predict(X_test_selected)
print(y_pred_nb)


print("Naive Bayes Accuracy:", accuracy_score(Y_test, y_pred_nb))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_nb))
print("Classification Report:\n", classification_report(Y_test, y_pred_nb))

[2 2 0 2 0 0 0 0 2 0 0 2 0 0 0 2 0 0 2 2 2 0 2 0 2 0 0 2 2 0 0 0 0 2 0 0 0
 2 2 0 0 0 0 0 0 0 2 0 2 0 2 2 2 2 0 0 2 0 0 0 2 0 0 0 2 0 0 0 2 2 0 0 0 2
 0 2 2 0 0 2]
Naive Bayes Accuracy: 0.9875
Confusion Matrix:
 [[49  1]
 [ 0 30]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [35]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train_selected, Y_train)
y_pred_mnb = mnb.predict(X_test_selected)
print(y_pred_mnb)


print("Multinomial NB Accuracy:", accuracy_score(Y_test, y_pred_mnb))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_mnb))
print("Classification Report:\n", classification_report(Y_test, y_pred_mnb))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]
Multinomial NB Accuracy: 0.625
Confusion Matrix:
 [[50  0]
 [30  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      1.00      0.77        50
           2       0.00      0.00      0.00        30

    accuracy                           0.62        80
   macro avg       0.31      0.50      0.38        80
weighted avg       0.39      0.62      0.48        80

c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [36]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train_selected, Y_train)
y_pred_bnb = bnb.predict(X_test_selected)
print(y_pred_bnb)

print("Bernoulli NB Accuracy:", accuracy_score(Y_test, y_pred_bnb))
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_bnb))
print("Classification Report:\n", classification_report(Y_test, y_pred_bnb))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]
Bernoulli NB Accuracy: 0.625
Confusion Matrix:
 [[50  0]
 [30  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.62      1.00      0.77        50
           2       0.00      0.00      0.00        30

    accuracy                           0.62        80
   macro avg       0.31      0.50      0.38        80
weighted avg       0.39      0.62      0.48        80

c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

TO COMPARE 3 ALGORITHMS METRICS

In [37]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = ['KNN', 'Decision Tree', 'Naive Bayes']

accuracy = [
    accuracy_score(Y_test, y_pred),
    accuracy_score(Y_test, y_pred_dt),
    accuracy_score(Y_test, y_pred_nb)
]

precision = [
    precision_score(Y_test, y_pred, pos_label=2),
    precision_score(Y_test, y_pred_dt, pos_label=2),
    precision_score(Y_test, y_pred_nb, pos_label=2)
]

recall = [
    recall_score(Y_test, y_pred, pos_label=2),
    recall_score(Y_test, y_pred_dt, pos_label=2),
    recall_score(Y_test, y_pred_nb, pos_label=2)
]

f1 = [
    f1_score(Y_test, y_pred, pos_label=2),
    f1_score(Y_test, y_pred_dt, pos_label=2),
    f1_score(Y_test, y_pred_nb, pos_label=2)
]

comparison_df = pd.DataFrame({
    'Model': models,
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall,
    'F1-Score': f1
})

print(comparison_df)

           Model  Accuracy  Precision    Recall  F1-Score
0            KNN    0.9875   0.967742  1.000000  0.983607
1  Decision Tree    0.9875   1.000000  0.966667  0.983051
2    Naive Bayes    0.9875   0.967742  1.000000  0.983607

METRICS- ROC AND AUC

In [41]:
from sklearn.metrics import roc_curve, auc

plt.figure()

# KNN
y_prob = knn.predict_proba(X_test_selected)[:, 1]
fpr_knn, tpr_knn, _ = roc_curve(Y_test, y_prob, pos_label=2)
plt.plot(fpr_knn, tpr_knn, label='KNN')

# Decision Tree
y_prob_dt = decision_tree.predict_proba(X_test_selected)[:, 1]
fpr_dt, tpr_dt, _ = roc_curve(Y_test, y_prob_dt, pos_label=2)
plt.plot(fpr_dt, tpr_dt, label='Decision Tree')

# Naive Bayes
y_prob_nb = nb.predict_proba(X_test_selected)[:, 1]
fpr_nb, tpr_nb, _ = roc_curve(Y_test, y_prob_nb, pos_label=2)
plt.plot(fpr_nb, tpr_nb, label='Naive Bayes')

# Random baseline
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend()
plt.show()

NameError: name 'plt' is not defined

This project predicts Chronic Kidney Disease using patient medical data.
Performed data cleaning, handled missing values, encoded categorical variables, applied feature scaling,
 and trained multiple machine learning models like KNN, Decision Tree, and Naive Bayes.
Evaluated them using accuracy, precision, recall, and confusion matrix. The model helps in early CKD detection, which is critical in healthcare

SVM ALGORITHM- 22/12/25

In [ ]:
from sklearn.svm import SVC ##imported svc

svm_method= SVC(kernel="linear")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [ ]:
svm_method= SVC(kernel="rbf")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [ ]:
svm_method= SVC(kernel="poly")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [ ]:
svm_method= SVC(kernel="sigmoid")

svm_method.fit(X_train_selected, Y_train)

y_predicted= svm_method.predict(X_test_selected)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(Y_test, y_pred))
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

Accuracy: 0.9875
[[49  1]
 [ 0 30]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        50
           2       0.97      1.00      0.98        30

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80

In [ ]:

import pickle

pickle.dump(models, open("kidney_model.pkl", "wb"))

print("✅ Model trained and saved as kidney_model.pkl")

✅ Model trained and saved as kidney_model.pkl